SELECT USER
FROM DUAL;
--==>> SCOTT


DROP TABLE TBL_MEMBER PURGE;
DROP SEQUENCE MEMBERSEQ;


-- ○ 실습 테이블 생성 (TBL_MEMBER)
CREATE TABLE TBL_MEMBER
( SID     NUMBER
, NAME    VARCHAR2(30)
, TEL     VARCHAR2(40)
, CONSTRAINT MEMBER_SID_PK PRIMARY KEY(SID)
);
--==>> Table TBL_MEMBER이(가) 생성되었습니다.

-- ○ 실습 테이블 생성 (TBL_MEMBERSCORE)
CREATE TABLE TBL_MEMBERSCORE
( SID   NUMBER
, KOR   NUMBER(3)
, ENG   NUMBER(3)
, MAT   NUMBER(3)
, CONSTRAINT MEMBERSCORE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT MEMBERSCORE_KOR_CK CHECK(KOR BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_ENG_CK CHECK(ENG BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_MAT_CH CHECK(MAT BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_SID_FK FOREIGN KEY(SID)
              REFERENCES TBL_MEMBER(SID)
);
--==>> Table TBL_MEMBERSCORE이(가) 생성되었습니다.


CREATE SEQUENCE MEMBERSEQ
NOCACHE;
--==>> Sequence MEMBERSEQ이(가) 생성되었습니다.


--○ 샘플 데이터 입력
INSERT INTO TBL_MEMBER(SID, NAME, TEL)
VALUES(MEMBERSEQ.NEXTVAL, '김진호', '010-1111-1111');
INSERT INTO TBL_MEMBER(SID, NAME, TEL)
VALUES(MEMBERSEQ.NEXTVAL, '정성찬', '010-2222-2222');
INSERT INTO TBL_MEMBER(SID, NAME, TEL)
VALUES(MEMBERSEQ.NEXTVAL, '이재학', '010-3333-3333');
INSERT INTO TBL_MEMBER(SID, NAME, TEL)
VALUES(MEMBERSEQ.NEXTVAL, '이지해', '010-4444-4444');
--==>> 1 행 이(가) 삽입되었습니다.


--○ 데이터 입력 쿼리문 구성
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '이지해', '010-4444-4444');

COMMIT;

SELECT *
FROM TBL_MEMBER;

SELECT *
FROM TBL_MEMBERSCORE;


--○ 데이터 입력 쿼리문 구성 (성적 정보 등록)
INSERT INTO TBL_MEMBERSCORE(SID, KOR, ENG, MAT)
VALUES(2, 90, 80, 70);

-- 한 줄 구성
INSERT INTO TBL_MEMBERSCORE(SID, KOR, ENG, MAT) VALUES(2, 90, 80, 70);

-- ○ 뷰 생성 (조인 출력영)
CREATE OR REPLACE VIEW VIEW_MEMBERSCORE
AS
SELECT N.SID, N.NAME 
     , NVL(S.KOR, 0) AS KOR
     , NVL(S.ENG, 0) AS ENG
     , NVL(S.MAT, 0) AS MAT
FROM TBL_MEMBER N, TBL_MEMBERSCORE S
WHERE N.SID = S.SID(+)
ORDER BY 1;



SELECT SID, NAME, KOR ,ENG, MAT, (KOR+ENG+MAT) AS TOT, ((KOR+ENG+MAT)/3) AS AVG, RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) AS RANK
FROM VIEW_MEMBERSCORE;



--○ 번호 검색 쿼리문 구성
SELECT SID, NAME, KOR, ENG, MAT
FROM VIEW_MEMBERSCORE
WHERE SID=1;

-- 한줄 구성
SELECT SID, NAME, KOR, ENG, MAT FROM VIEW_MEMBERSCORE WHERE SID=1
;

--○ 데이터 수정 쿼리문 구성 (성적 데이터)
UPDATE TBL_MEMBERSCORE
SET KOR=100, ENG=100, MAT=100
WHERE SID=1;

-- 한줄 구성
UPDATE TBL_MEMBERSCORE SET KOR=100, ENG=100, MAT=100 WHERE SID=1
;


--○ 데이터 삭제 쿼리문 구성 (성적 데이타)
DELETE
FROM TBL_MEMBERSCORE
WHERE SID=1;

-- 한줄 구성
DELETE FROM TBL_MEMBERSCORE WHERE SID=1
;


UPDATE TBL_MEMBER
SET NAME='정현석', TEL='010-1111-1111'
WHERE SID=1;

-- 한 줄 구성
UPDATE TBL_MEMBER SET NAME='정현석', TEL='010-1111-1111' WHERE SID=1;


-- ○ TBL_MEMBERSCORE 의 SID 만족하는
--    레코드 수 확인 (회원 정보 삭제를 위해 필요한 쿼리문) 쿼리문 구성
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERSCORE
WHERE SID=1;

-- 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERSCORE WHERE SID=1
;


-- ○ 김진호 회원의 성적 입력
INSERT INTO TBL_MEMBERSCORE(SID, KOR, ENG, MAT)
VALUES(1, 90, 80, 70);

COMMIT;


SELECT *
FROM VIEW_MEMBERSCORE;

SELECT *
FROM TBL_MEMBERSCORE;

SELECT SID, NAME, TEL FROM TBL_MEMBER;

-- 수정 쿼리문
UPDATE TBL_MEMBER
SET NAME = '김지노',TEL = '010-5823-4222'
WHERE SID = 1;

-- 수정 쿼리문 한줄 구성
UPDATE TBL_MEMBER SET NAME = '김지노',TEL = '010-5823-4222' WHERE SID = 1;

-- 삭제 쿼리문
DELETE
FROM TBL_MEMBER
WHERE SID = 1;
-- 삭제 쿼리문 한줄 구성
DELETE FROM TBL_MEMBER WHERE SID = 1;
ROLLBACK;


-- 번호 검색 
SELECT SID, NAME, TEL
FROM TBL_MEMBER
WHERE SID = 1;

-- 번호 검색 한줄 구성
SELECT SID, NAME, TEL FROM TBL_MEMBER WHERE SID = 1;


SELECT *
FROM TBL_MEMBERSCORE;