SELECT USER
FROM DUAL;
--==>> TRY

/* 기업 테이블 */
CREATE TABLE CMPNY_TBL (
	CMPNY_ID CHAR(10) NOT NULL, /* 사업자 번호 */
	CMPNY_CTGY_ID NUMBER NOT NULL, /* 기업 카테고리 코드 */
	NAME VARCHAR2(40) NOT NULL, /* 기업 이름 */
	CTNT VARCHAR2(400) NOT NULL, /* 기업 내용 */
	PWD VARCHAR2(20) NOT NULL, /* 비밀번호 */
	EMAIL VARCHAR2(30) NOT NULL, /* 이메일 */
	TEL CHAR(13) NOT NULL, /* 휴대폰 */
	HMPG VARCHAR2(50) NOT NULL, /* 홈페이지 */
	ADDR_NO CHAR(5) NOT NULL, /* 우편 번호 */
	ADDR1 VARCHAR2(50) NOT NULL, /* 주소 */
	ADDR2 VARCHAR2(50) NOT NULL, /* 상세 주소 */
	WTDRL CHAR(1) NOT NULL /* 탈퇴 여부 */
);

COMMENT ON TABLE CMPNY_TBL IS '기업 테이블';

COMMENT ON COLUMN CMPNY_TBL.CMPNY_ID IS '사업자 번호';

COMMENT ON COLUMN CMPNY_TBL.CMPNY_CTGY_ID IS '기업 카테고리 코드';

COMMENT ON COLUMN CMPNY_TBL.NAME IS '기업 이름';

COMMENT ON COLUMN CMPNY_TBL.CTNT IS '기업 내용';

COMMENT ON COLUMN CMPNY_TBL.PWD IS '비밀번호';

COMMENT ON COLUMN CMPNY_TBL.EMAIL IS '이메일';

COMMENT ON COLUMN CMPNY_TBL.TEL IS '휴대폰';

COMMENT ON COLUMN CMPNY_TBL.HMPG IS '홈페이지';

COMMENT ON COLUMN CMPNY_TBL.ADDR_NO IS '우편 번호';

COMMENT ON COLUMN CMPNY_TBL.ADDR1 IS '주소';

COMMENT ON COLUMN CMPNY_TBL.ADDR2 IS '상세 주소';

COMMENT ON COLUMN CMPNY_TBL.WTDRL IS '탈퇴 여부';

CREATE UNIQUE INDEX PK_CMPNY_TBL
	ON CMPNY_TBL (
		CMPNY_ID ASC
	);

ALTER TABLE CMPNY_TBL
	ADD
		CONSTRAINT PK_CMPNY_TBL
		PRIMARY KEY (
			CMPNY_ID
		);

/* 회원 테이블 */
CREATE TABLE USR_TBL (
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	GNDR_CD NUMBER NOT NULL, /* 성별 코드 */
	NAME VARCHAR2(15) NOT NULL, /* 이름 */
	PWD VARCHAR2(20), /* 비밀번호 */
	EMAIL VARCHAR2(50), /* 이메일 */
	TEL CHAR(13), /* 휴대폰 */
	BRTHDAY DATE, /* 생년월일 */
	ADDR_NO CHAR(5), /* 우편 번호 */
	ADDR1 VARCHAR2(50), /* 주소 */
	ADDR2 VARCHAR2(50) /* 상세 주소 */
);

COMMENT ON TABLE USR_TBL IS '회원 테이블';

COMMENT ON COLUMN USR_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN USR_TBL.GNDR_CD IS '성별 코드';

COMMENT ON COLUMN USR_TBL.NAME IS '이름';

COMMENT ON COLUMN USR_TBL.PWD IS '비밀번호';

COMMENT ON COLUMN USR_TBL.EMAIL IS '이메일';

COMMENT ON COLUMN USR_TBL.TEL IS '휴대폰';

COMMENT ON COLUMN USR_TBL.BRTHDAY IS '생년월일';

COMMENT ON COLUMN USR_TBL.ADDR_NO IS '우편 번호';

COMMENT ON COLUMN USR_TBL.ADDR1 IS '주소';

COMMENT ON COLUMN USR_TBL.ADDR2 IS '상세 주소';

CREATE UNIQUE INDEX PK_USR_TBL
	ON USR_TBL (
		USR_ID ASC
	);

ALTER TABLE USR_TBL
	ADD
		CONSTRAINT PK_USR_TBL
		PRIMARY KEY (
			USR_ID
		);

/* 상품 테이블 */
CREATE TABLE PROD_TBL (
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	CMPNY_ID CHAR(10) NOT NULL, /* 사업자 번호 */
	PROD_POST_CD NUMBER NOT NULL, /* 상품 게시 코드 */
	NAME VARCHAR2(50) NOT NULL, /* 상품 이름 */
	PRC NUMBER NOT NULL, /* 상품 가격 */
	DC CHAR(1) NOT NULL /* 상품 할인 여부 */
);

COMMENT ON TABLE PROD_TBL IS '상품 테이블';

COMMENT ON COLUMN PROD_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN PROD_TBL.CMPNY_ID IS '사업자 번호';

COMMENT ON COLUMN PROD_TBL.PROD_POST_CD IS '상품 게시 코드';

COMMENT ON COLUMN PROD_TBL.NAME IS '상품 이름';

COMMENT ON COLUMN PROD_TBL.PRC IS '상품 가격';

COMMENT ON COLUMN PROD_TBL.DC IS '상품 할인 여부';

CREATE UNIQUE INDEX PK_PROD_TBL
	ON PROD_TBL (
		PROD_CD ASC
	);

ALTER TABLE PROD_TBL
	ADD
		CONSTRAINT PK_PROD_TBL
		PRIMARY KEY (
			PROD_CD
		);

/* 예약 테이블 */
CREATE TABLE RSVTN_TBL (
	RSVTN_CD NUMBER NOT NULL, /* 예약 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	DAY DATE NOT NULL, /* 예약 신청일 */
	VST DATE NOT NULL, /* 예약 방문일 */
	INQY VARCHAR2(200), /* 기타 문의사항 */
	RSLT CHAR(1) NOT NULL /* 예약 결과 */
);

COMMENT ON TABLE RSVTN_TBL IS '예약 테이블';

COMMENT ON COLUMN RSVTN_TBL.RSVTN_CD IS '예약 코드';

COMMENT ON COLUMN RSVTN_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN RSVTN_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN RSVTN_TBL.DAY IS '예약 신청일';

COMMENT ON COLUMN RSVTN_TBL.VST IS '예약 방문일';

COMMENT ON COLUMN RSVTN_TBL.INQY IS '기타 문의사항';

COMMENT ON COLUMN RSVTN_TBL.RSLT IS '예약 결과';

CREATE UNIQUE INDEX PK_RSVTN_TBL
	ON RSVTN_TBL (
		RSVTN_CD ASC
	);

ALTER TABLE RSVTN_TBL
	ADD
		CONSTRAINT PK_RSVTN_TBL
		PRIMARY KEY (
			RSVTN_CD
		);

/* 찜 테이블 */
CREATE TABLE SEL_TBL (
	SEL_CD NUMBER NOT NULL, /* 찜 코드 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	DT DATE NOT NULL /* 찜 시간 */
);

COMMENT ON TABLE SEL_TBL IS '찜 테이블';

COMMENT ON COLUMN SEL_TBL.SEL_CD IS '찜 코드';

COMMENT ON COLUMN SEL_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN SEL_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN SEL_TBL.DT IS '찜 시간';

CREATE UNIQUE INDEX PK_SEL_TBL
	ON SEL_TBL (
		SEL_CD ASC
	);

ALTER TABLE SEL_TBL
	ADD
		CONSTRAINT PK_SEL_TBL
		PRIMARY KEY (
			SEL_CD
		);

/* 상담 테이블 */
CREATE TABLE ADV_TBL (
	ADV_CD NUMBER NOT NULL, /* 상담 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	SBJCT VARCHAR2(200) NOT NULL, /* 상담 제목 */
	CTNT VARCHAR2(400) NOT NULL, /* 상담 내용 */
	DT DATE NOT NULL /* 상담 작성일 */
);

COMMENT ON TABLE ADV_TBL IS '상담 테이블';

COMMENT ON COLUMN ADV_TBL.ADV_CD IS '상담 코드';

COMMENT ON COLUMN ADV_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN ADV_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN ADV_TBL.SBJCT IS '상담 제목';

COMMENT ON COLUMN ADV_TBL.CTNT IS '상담 내용';

COMMENT ON COLUMN ADV_TBL.DT IS '상담 작성일';

CREATE UNIQUE INDEX PK_ADV_TBL
	ON ADV_TBL (
		ADV_CD ASC
	);

ALTER TABLE ADV_TBL
	ADD
		CONSTRAINT PK_ADV_TBL
		PRIMARY KEY (
			ADV_CD
		);

/* 회원 QNA 테이블 */
CREATE TABLE QUSR_TBL (
	USR_QNA_CD NUMBER NOT NULL, /* 회원 QNA 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	SBJCT VARCHAR2(100) NOT NULL, /* 회원 QNA 제목 */
	CTNT VARCHAR2(2000) NOT NULL, /* 회원 QNA 내용 */
	DT DATE NOT NULL, /* 회원 QNA 작성시간 */
	CNT NUMBER NOT NULL, /* 회원 QNA 조회수 */
	PWD VARCHAR2(20) /* 회원 QNA 비밀번호 */
);

COMMENT ON TABLE QUSR_TBL IS '회원 QNA 테이블';

COMMENT ON COLUMN QUSR_TBL.USR_QNA_CD IS '회원 QNA 코드';

COMMENT ON COLUMN QUSR_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN QUSR_TBL.SBJCT IS '회원 QNA 제목';

COMMENT ON COLUMN QUSR_TBL.CTNT IS '회원 QNA 내용';

COMMENT ON COLUMN QUSR_TBL.DT IS '회원 QNA 작성시간';

COMMENT ON COLUMN QUSR_TBL.CNT IS '회원 QNA 조회수';

COMMENT ON COLUMN QUSR_TBL.PWD IS '회원 QNA 비밀번호';

CREATE UNIQUE INDEX PK_QUSR_TBL
	ON QUSR_TBL (
		USR_QNA_CD ASC
	);

ALTER TABLE QUSR_TBL
	ADD
		CONSTRAINT PK_QUSR_TBL
		PRIMARY KEY (
			USR_QNA_CD
		);

/* 상품평 테이블 */
CREATE TABLE PROD_CMT_TBL (
	PROD_CMT_CD NUMBER NOT NULL, /* 상품평 코드 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	CTNT VARCHAR2(400) NOT NULL, /* 상품평 내용 */
	DT DATE NOT NULL, /* 상품평 작성일 */
	SCR NUMBER(5) NOT NULL /* 상품평 평점 */
);

COMMENT ON TABLE PROD_CMT_TBL IS '상품평 테이블';

COMMENT ON COLUMN PROD_CMT_TBL.PROD_CMT_CD IS '상품평 코드';

COMMENT ON COLUMN PROD_CMT_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN PROD_CMT_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN PROD_CMT_TBL.CTNT IS '상품평 내용';

COMMENT ON COLUMN PROD_CMT_TBL.DT IS '상품평 작성일';

COMMENT ON COLUMN PROD_CMT_TBL.SCR IS '상품평 평점';

CREATE UNIQUE INDEX PK_PROD_CMT_TBL
	ON PROD_CMT_TBL (
		PROD_CMT_CD ASC
	);

ALTER TABLE PROD_CMT_TBL
	ADD
		CONSTRAINT PK_PROD_CMT_TBL
		PRIMARY KEY (
			PROD_CMT_CD
		);

/* 기업 카테고리 테이블 */
CREATE TABLE CMPNY_CTGY_TBL (
	CMPNY_CTGY_ID NUMBER NOT NULL, /* 기업 카테고리 코드 */
	NAME VARCHAR2(30) NOT NULL /* 기업 카테고리 이름 */
);

COMMENT ON TABLE CMPNY_CTGY_TBL IS '기업 카테고리 테이블';

COMMENT ON COLUMN CMPNY_CTGY_TBL.CMPNY_CTGY_ID IS '기업 카테고리 코드';

COMMENT ON COLUMN CMPNY_CTGY_TBL.NAME IS '기업 카테고리 이름';

CREATE UNIQUE INDEX PK_CMPNY_CTGY_TBL
	ON CMPNY_CTGY_TBL (
		CMPNY_CTGY_ID ASC
	);

ALTER TABLE CMPNY_CTGY_TBL
	ADD
		CONSTRAINT PK_CMPNY_CTGY_TBL
		PRIMARY KEY (
			CMPNY_CTGY_ID
		);

/* 광고 승인 테이블 */
CREATE TABLE AD_CNFM_TBL (
	ADVT_CD NUMBER NOT NULL, /* 광고 승인 코드 */
	AD_PT_CD NUMBER NOT NULL, /* 광고 게시 코드 */
	PMT_CD NUMBER NOT NULL /* 결제 코드 */
);

COMMENT ON TABLE AD_CNFM_TBL IS '광고 승인 테이블';

COMMENT ON COLUMN AD_CNFM_TBL.ADVT_CD IS '광고 승인 코드';

COMMENT ON COLUMN AD_CNFM_TBL.AD_PT_CD IS '광고 게시 코드';

COMMENT ON COLUMN AD_CNFM_TBL.PMT_CD IS '결제 코드';

CREATE UNIQUE INDEX PK_AD_CNFM_TBL
	ON AD_CNFM_TBL (
		ADVT_CD ASC
	);

ALTER TABLE AD_CNFM_TBL
	ADD
		CONSTRAINT PK_AD_CNFM_TBL
		PRIMARY KEY (
			ADVT_CD
		);

/* 결제 테이블 */
CREATE TABLE PMT_TBL (
	PMT_CD NUMBER NOT NULL, /* 결제 코드 */
	ADVT_REQ_CD NUMBER NOT NULL, /* 광고 요청 코드 */
	PMT_CTGY_CD NUMBER NOT NULL, /* 결제 카테고리 코드 */
	DT DATE NOT NULL /* 결제일 */
);

COMMENT ON TABLE PMT_TBL IS '결제 테이블';

COMMENT ON COLUMN PMT_TBL.PMT_CD IS '결제 코드';

COMMENT ON COLUMN PMT_TBL.ADVT_REQ_CD IS '광고 요청 코드';

COMMENT ON COLUMN PMT_TBL.PMT_CTGY_CD IS '결제 카테고리 코드';

COMMENT ON COLUMN PMT_TBL.DT IS '결제일';

CREATE UNIQUE INDEX PK_PMT_TBL
	ON PMT_TBL (
		PMT_CD ASC
	);

ALTER TABLE PMT_TBL
	ADD
		CONSTRAINT PK_PMT_TBL
		PRIMARY KEY (
			PMT_CD
		);

/* 회원 1차 경고 테이블 */
CREATE TABLE USR_WAR1_TBL (
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	CTNT VARCHAR2(100) NOT NULL /* 경고 내용 */
);

COMMENT ON TABLE USR_WAR1_TBL IS '회원 1차 경고 테이블';

COMMENT ON COLUMN USR_WAR1_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN USR_WAR1_TBL.CTNT IS '경고 내용';

CREATE UNIQUE INDEX PK_USR_WAR1_TBL
	ON USR_WAR1_TBL (
		USR_ID ASC
	);

ALTER TABLE USR_WAR1_TBL
	ADD
		CONSTRAINT PK_USR_WAR1_TBL
		PRIMARY KEY (
			USR_ID
		);

/* FAQ 테이블 */
CREATE TABLE FAQ_TBL (
	FAQ_CD NUMBER NOT NULL, /* FAQ 코드 */
	FAQ_CTGY_CD NUMBER NOT NULL, /* FAQ 카테고리 코드 */
	ADMIN_CD CHAR(5) NOT NULL, /* 관리자 코드 */
	SBJCT VARCHAR2(200) NOT NULL, /* FAQ 제목 */
	CTNT VARCHAR2(2000) NOT NULL, /* FAQ 내용 */
	DT DATE NOT NULL, /* FAQ 작성일 */
	CNT NUMBER NOT NULL /* FAQ 조회수 */
);

COMMENT ON TABLE FAQ_TBL IS 'FAQ 테이블';

COMMENT ON COLUMN FAQ_TBL.FAQ_CD IS 'FAQ 코드';

COMMENT ON COLUMN FAQ_TBL.FAQ_CTGY_CD IS 'FAQ 카테고리 코드';

COMMENT ON COLUMN FAQ_TBL.ADMIN_CD IS '관리자 코드';

COMMENT ON COLUMN FAQ_TBL.SBJCT IS 'FAQ 제목';

COMMENT ON COLUMN FAQ_TBL.CTNT IS 'FAQ 내용';

COMMENT ON COLUMN FAQ_TBL.DT IS 'FAQ 작성일';

COMMENT ON COLUMN FAQ_TBL.CNT IS 'FAQ 조회수';

CREATE UNIQUE INDEX PK_FAQ_TBL
	ON FAQ_TBL (
		FAQ_CD ASC
	);

ALTER TABLE FAQ_TBL
	ADD
		CONSTRAINT PK_FAQ_TBL
		PRIMARY KEY (
			FAQ_CD
		);

/* 이미지 테이블 */
CREATE TABLE IMG_TBL (
	IMG_CD NUMBER NOT NULL, /* 이미지 코드 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	PTH VARCHAR2(50) NOT NULL /* 이미지 경로 */
);

COMMENT ON TABLE IMG_TBL IS '이미지 테이블';

COMMENT ON COLUMN IMG_TBL.IMG_CD IS '이미지 코드';

COMMENT ON COLUMN IMG_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN IMG_TBL.PTH IS '이미지 경로';

CREATE UNIQUE INDEX PK_IMG_TBL
	ON IMG_TBL (
		IMG_CD ASC
	);

ALTER TABLE IMG_TBL
	ADD
		CONSTRAINT PK_IMG_TBL
		PRIMARY KEY (
			IMG_CD
		);

/* 결제 카테고리 테이블 */
CREATE TABLE PMT_CTGY_TBL (
	PMT_CTGY_CD NUMBER NOT NULL, /* 결제 카테고리 코드 */
	NAME VARCHAR2(20) NOT NULL /* 결제 카테고리 이름 */
);

COMMENT ON TABLE PMT_CTGY_TBL IS '결제 카테고리 테이블';

COMMENT ON COLUMN PMT_CTGY_TBL.PMT_CTGY_CD IS '결제 카테고리 코드';

COMMENT ON COLUMN PMT_CTGY_TBL.NAME IS '결제 카테고리 이름';

CREATE UNIQUE INDEX PK_PMT_CTGY_TBL
	ON PMT_CTGY_TBL (
		PMT_CTGY_CD ASC
	);

ALTER TABLE PMT_CTGY_TBL
	ADD
		CONSTRAINT PK_PMT_CTGY_TBL
		PRIMARY KEY (
			PMT_CTGY_CD
		);

/* 광고 게시 테이블(상태를 나타냄) */
CREATE TABLE AD_PT_TBL (
	AD_PT_CD NUMBER NOT NULL, /* 광고 게시 코드 */
	STT VARCHAR2(10) NOT NULL /* 광고 게시 상태 */
);

COMMENT ON TABLE AD_PT_TBL IS '광고 게시 테이블(상태를 나타냄)';

COMMENT ON COLUMN AD_PT_TBL.AD_PT_CD IS '광고 게시 코드';

COMMENT ON COLUMN AD_PT_TBL.STT IS '광고 게시 상태';

CREATE UNIQUE INDEX PK_AD_PT_TBL
	ON AD_PT_TBL (
		AD_PT_CD ASC
	);

ALTER TABLE AD_PT_TBL
	ADD
		CONSTRAINT PK_AD_PT_TBL
		PRIMARY KEY (
			AD_PT_CD
		);

/* 견적 테이블 */
CREATE TABLE EST_TBL (
	EST_CD NUMBER NOT NULL, /* 견적 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	DTL_PROD_CD NUMBER NOT NULL, /* 상세 상품 코드 */
	PRC NUMBER NOT NULL /* 견적 */
);

COMMENT ON TABLE EST_TBL IS '견적 테이블';

COMMENT ON COLUMN EST_TBL.EST_CD IS '견적 코드';

COMMENT ON COLUMN EST_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN EST_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN EST_TBL.DTL_PROD_CD IS '상세 상품 코드';

COMMENT ON COLUMN EST_TBL.PRC IS '견적';

CREATE UNIQUE INDEX PK_EST_TBL
	ON EST_TBL (
		EST_CD ASC
	);

ALTER TABLE EST_TBL
	ADD
		CONSTRAINT PK_EST_TBL
		PRIMARY KEY (
			EST_CD
		);

/* 공지사항 테이블 */
CREATE TABLE NTC_TBL (
	NTC_CD NUMBER NOT NULL, /* 공지사항 코드 */
	ADMIN_CD CHAR(5) NOT NULL, /* 관리자 코드 */
	SBJCT VARCHAR2(100) NOT NULL, /* 공지사항 제목 */
	CTNT VARCHAR2(2000) NOT NULL, /* 공지사항 내용 */
	DT DATE NOT NULL, /* 공지사항 작성일 */
	CNT NUMBER NOT NULL /* 공지사항 조회수 */
);

COMMENT ON TABLE NTC_TBL IS '공지사항 테이블';

COMMENT ON COLUMN NTC_TBL.NTC_CD IS '공지사항 코드';

COMMENT ON COLUMN NTC_TBL.ADMIN_CD IS '관리자 코드';

COMMENT ON COLUMN NTC_TBL.SBJCT IS '공지사항 제목';

COMMENT ON COLUMN NTC_TBL.CTNT IS '공지사항 내용';

COMMENT ON COLUMN NTC_TBL.DT IS '공지사항 작성일';

COMMENT ON COLUMN NTC_TBL.CNT IS '공지사항 조회수';

CREATE UNIQUE INDEX PK_NTC_TBL
	ON NTC_TBL (
		NTC_CD ASC
	);

ALTER TABLE NTC_TBL
	ADD
		CONSTRAINT PK_NTC_TBL
		PRIMARY KEY (
			NTC_CD
		);

/* 상품평 댓글 테이블 */
CREATE TABLE RVW_CMT_TBL (
	RVW_CMT_CD NUMBER NOT NULL, /* 상품평 댓글 코드 */
	PROD_CMT_CD NUMBER NOT NULL, /* 상품평 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	CTNT VARCHAR2(400) NOT NULL, /* 상품평 댓글 내용 */
	DT DATE NOT NULL /* 상품평 댓글 등록시간 */
);

COMMENT ON TABLE RVW_CMT_TBL IS '상품평 댓글 테이블';

COMMENT ON COLUMN RVW_CMT_TBL.RVW_CMT_CD IS '상품평 댓글 코드';

COMMENT ON COLUMN RVW_CMT_TBL.PROD_CMT_CD IS '상품평 코드';

COMMENT ON COLUMN RVW_CMT_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN RVW_CMT_TBL.CTNT IS '상품평 댓글 내용';

COMMENT ON COLUMN RVW_CMT_TBL.DT IS '상품평 댓글 등록시간';

CREATE UNIQUE INDEX PK_RVW_CMT_TBL
	ON RVW_CMT_TBL (
		RVW_CMT_CD ASC
	);

ALTER TABLE RVW_CMT_TBL
	ADD
		CONSTRAINT PK_RVW_CMT_TBL
		PRIMARY KEY (
			RVW_CMT_CD
		);

/* FAQ 카테고리 테이블 */
CREATE TABLE FAQ_CTGY_TBL (
	FAQ_CTGY_CD NUMBER NOT NULL, /* FAQ 카테고리 코드 */
	NAME VARCHAR2(20) NOT NULL /* FAQ 카테고리 이름 */
);

COMMENT ON TABLE FAQ_CTGY_TBL IS 'FAQ 카테고리 테이블';

COMMENT ON COLUMN FAQ_CTGY_TBL.FAQ_CTGY_CD IS 'FAQ 카테고리 코드';

COMMENT ON COLUMN FAQ_CTGY_TBL.NAME IS 'FAQ 카테고리 이름';

CREATE UNIQUE INDEX PK_FAQ_CTGY_TBL
	ON FAQ_CTGY_TBL (
		FAQ_CTGY_CD ASC
	);

ALTER TABLE FAQ_CTGY_TBL
	ADD
		CONSTRAINT PK_FAQ_CTGY_TBL
		PRIMARY KEY (
			FAQ_CTGY_CD
		);

/* 상담 댓글 테이블 */
CREATE TABLE ADV_CMT_TBL (
	ADV_CMT_CD NUMBER NOT NULL, /* 상담 댓글 코드 */
	ADV_CD NUMBER NOT NULL, /* 상담 코드 */
	CTNT VARCHAR2(400) NOT NULL, /* 상담 댓글 내용 */
	DT DATE NOT NULL /* 상담 댓글 등록시간 */
);

COMMENT ON TABLE ADV_CMT_TBL IS '상담 댓글 테이블';

COMMENT ON COLUMN ADV_CMT_TBL.ADV_CMT_CD IS '상담 댓글 코드';

COMMENT ON COLUMN ADV_CMT_TBL.ADV_CD IS '상담 코드';

COMMENT ON COLUMN ADV_CMT_TBL.CTNT IS '상담 댓글 내용';

COMMENT ON COLUMN ADV_CMT_TBL.DT IS '상담 댓글 등록시간';

CREATE UNIQUE INDEX PK_ADV_CMT_TBL
	ON ADV_CMT_TBL (
		ADV_CMT_CD ASC
	);

ALTER TABLE ADV_CMT_TBL
	ADD
		CONSTRAINT PK_ADV_CMT_TBL
		PRIMARY KEY (
			ADV_CMT_CD
		);

/* 관리자 테이블 */
CREATE TABLE ADMIN_TBL (
	ADMIN_CD CHAR(5) NOT NULL, /* 관리자 코드 */
	PWD VARCHAR2(20) NOT NULL /* 비밀번호 */
);

COMMENT ON TABLE ADMIN_TBL IS '관리자 테이블';

COMMENT ON COLUMN ADMIN_TBL.ADMIN_CD IS '관리자 코드';

COMMENT ON COLUMN ADMIN_TBL.PWD IS '비밀번호';

CREATE UNIQUE INDEX PK_ADMIN_TBL
	ON ADMIN_TBL (
		ADMIN_CD ASC
	);

ALTER TABLE ADMIN_TBL
	ADD
		CONSTRAINT PK_ADMIN_TBL
		PRIMARY KEY (
			ADMIN_CD
		);

/* 기업 QNA 테이블 */
CREATE TABLE QCMPNY_TBL (
	CMPNY_QNA_CD NUMBER NOT NULL, /* 기업 QNA 코드 */
	CMPNY_ID CHAR(10) NOT NULL, /* 사업자 번호 */
	SBJCT VARCHAR2(100) NOT NULL, /* 기업 QNA 제목 */
	CTNT VARCHAR2(2000) NOT NULL, /* 기업 QNA 내용 */
	DT DATE NOT NULL, /* 기업 QNA 작성시간 */
	CNT NUMBER NOT NULL, /* 기업 QNA 조회수 */
	PWD VARCHAR2(20) /* 기업 QNA 비밀번호 */
);

COMMENT ON TABLE QCMPNY_TBL IS '기업 QNA 테이블';

COMMENT ON COLUMN QCMPNY_TBL.CMPNY_QNA_CD IS '기업 QNA 코드';

COMMENT ON COLUMN QCMPNY_TBL.CMPNY_ID IS '사업자 번호';

COMMENT ON COLUMN QCMPNY_TBL.SBJCT IS '기업 QNA 제목';

COMMENT ON COLUMN QCMPNY_TBL.CTNT IS '기업 QNA 내용';

COMMENT ON COLUMN QCMPNY_TBL.DT IS '기업 QNA 작성시간';

COMMENT ON COLUMN QCMPNY_TBL.CNT IS '기업 QNA 조회수';

COMMENT ON COLUMN QCMPNY_TBL.PWD IS '기업 QNA 비밀번호';

CREATE UNIQUE INDEX PK_QCMPNY_TBL
	ON QCMPNY_TBL (
		CMPNY_QNA_CD ASC
	);

ALTER TABLE QCMPNY_TBL
	ADD
		CONSTRAINT PK_QCMPNY_TBL
		PRIMARY KEY (
			CMPNY_QNA_CD
		);

/* 기업 1차 경고 테이블 */
CREATE TABLE CMPNY_WAR1_TBL (
	CMPNY_ID CHAR(10) NOT NULL, /* 사업자 번호 */
	CTNT VARCHAR2(100) NOT NULL /* 경고 내용 */
);

COMMENT ON TABLE CMPNY_WAR1_TBL IS '기업 1차 경고 테이블';

COMMENT ON COLUMN CMPNY_WAR1_TBL.CMPNY_ID IS '사업자 번호';

COMMENT ON COLUMN CMPNY_WAR1_TBL.CTNT IS '경고 내용';

CREATE UNIQUE INDEX PK_CMPNY_WAR1_TBL
	ON CMPNY_WAR1_TBL (
		CMPNY_ID ASC
	);

ALTER TABLE CMPNY_WAR1_TBL
	ADD
		CONSTRAINT PK_CMPNY_WAR1_TBL
		PRIMARY KEY (
			CMPNY_ID
		);

/* QNA 관리자-회원 댓글 테이블 */
CREATE TABLE QAU_CMT_TBL (
	USR_ADMIN_CMT_CD NUMBER NOT NULL, /* QNA 관리자-회원 댓글 코드 */
	USR_QNA_CD NUMBER NOT NULL, /* 회원 QNA 코드 */
	ADMIN_CD CHAR(5) NOT NULL, /* 관리자 코드 */
	CTNT VARCHAR2(400) NOT NULL, /* QNA 관리자-회원 댓글 내용 */
	DT DATE NOT NULL /* QNA 관리자-회원 댓글 등록시간 */
);

COMMENT ON TABLE QAU_CMT_TBL IS 'QNA 관리자-회원 댓글 테이블';

COMMENT ON COLUMN QAU_CMT_TBL.USR_ADMIN_CMT_CD IS 'QNA 관리자-회원 댓글 코드';

COMMENT ON COLUMN QAU_CMT_TBL.USR_QNA_CD IS '회원 QNA 코드';

COMMENT ON COLUMN QAU_CMT_TBL.ADMIN_CD IS '관리자 코드';

COMMENT ON COLUMN QAU_CMT_TBL.CTNT IS 'QNA 관리자-회원 댓글 내용';

COMMENT ON COLUMN QAU_CMT_TBL.DT IS 'QNA 관리자-회원 댓글 등록시간';

CREATE UNIQUE INDEX PK_QAU_CMT_TBL
	ON QAU_CMT_TBL (
		USR_ADMIN_CMT_CD ASC
	);

ALTER TABLE QAU_CMT_TBL
	ADD
		CONSTRAINT PK_QAU_CMT_TBL
		PRIMARY KEY (
			USR_ADMIN_CMT_CD
		);

/* QNA 관리자-기업 댓글 테이블 */
CREATE TABLE QAC_CMT_TBL (
	QNA_ADMIN_CMPNY_CD NUMBER NOT NULL, /* QNA 관리자-기업 댓글 코드 */
	CMPNY_QNA_CD NUMBER NOT NULL, /* 기업 QNA 코드 */
	ADMIN_CD CHAR(5) NOT NULL, /* 관리자 코드 */
	CTNT VARCHAR2(400) NOT NULL, /* QNA 관리자-기업 댓글 내용 */
	DT DATE NOT NULL /* QNA 관리자-기업 댓글 등록시간 */
);

COMMENT ON TABLE QAC_CMT_TBL IS 'QNA 관리자-기업 댓글 테이블';

COMMENT ON COLUMN QAC_CMT_TBL.QNA_ADMIN_CMPNY_CD IS 'QNA 관리자-기업 댓글 코드';

COMMENT ON COLUMN QAC_CMT_TBL.CMPNY_QNA_CD IS '기업 QNA 코드';

COMMENT ON COLUMN QAC_CMT_TBL.ADMIN_CD IS '관리자 코드';

COMMENT ON COLUMN QAC_CMT_TBL.CTNT IS 'QNA 관리자-기업 댓글 내용';

COMMENT ON COLUMN QAC_CMT_TBL.DT IS 'QNA 관리자-기업 댓글 등록시간';

CREATE UNIQUE INDEX PK_QAC_CMT_TBL
	ON QAC_CMT_TBL (
		QNA_ADMIN_CMPNY_CD ASC
	);

ALTER TABLE QAC_CMT_TBL
	ADD
		CONSTRAINT PK_QAC_CMT_TBL
		PRIMARY KEY (
			QNA_ADMIN_CMPNY_CD
		);

/* 열람 테이블 */
CREATE TABLE VW_TBL (
	VW_CD NUMBER NOT NULL, /* 열람 코드 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	DT DATE NOT NULL /* 열람 시간 */
);

COMMENT ON TABLE VW_TBL IS '열람 테이블';

COMMENT ON COLUMN VW_TBL.VW_CD IS '열람 코드';

COMMENT ON COLUMN VW_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN VW_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN VW_TBL.DT IS '열람 시간';

CREATE UNIQUE INDEX PK_VW_TBL
	ON VW_TBL (
		VW_CD ASC
	);

ALTER TABLE VW_TBL
	ADD
		CONSTRAINT PK_VW_TBL
		PRIMARY KEY (
			VW_CD
		);

/* 상세 상품 테이블 */
CREATE TABLE DTL_PROD_TBL (
	DTL_PROD_CD NUMBER NOT NULL, /* 상세 상품 코드 */
	CMPNY_ID CHAR(10) NOT NULL, /* 사업자 번호 */
	NAME VARCHAR2(50) NOT NULL, /* 상세 상품 이름 */
	PRC NUMBER NOT NULL /* 상세 상품 가격 */
);

COMMENT ON TABLE DTL_PROD_TBL IS '상세 상품 테이블';

COMMENT ON COLUMN DTL_PROD_TBL.DTL_PROD_CD IS '상세 상품 코드';

COMMENT ON COLUMN DTL_PROD_TBL.CMPNY_ID IS '사업자 번호';

COMMENT ON COLUMN DTL_PROD_TBL.NAME IS '상세 상품 이름';

COMMENT ON COLUMN DTL_PROD_TBL.PRC IS '상세 상품 가격';

CREATE UNIQUE INDEX PK_DTL_PROD_TBL
	ON DTL_PROD_TBL (
		DTL_PROD_CD ASC
	);

ALTER TABLE DTL_PROD_TBL
	ADD
		CONSTRAINT PK_DTL_PROD_TBL
		PRIMARY KEY (
			DTL_PROD_CD
		);

/* 성별 테이블 */
CREATE TABLE GNDR_TBL (
	GNDR_CD NUMBER NOT NULL, /* 성별 코드 */
	CTNT VARCHAR2(6) NOT NULL /* 성별 내용 */
);

COMMENT ON TABLE GNDR_TBL IS '성별 테이블';

COMMENT ON COLUMN GNDR_TBL.GNDR_CD IS '성별 코드';

COMMENT ON COLUMN GNDR_TBL.CTNT IS '성별 내용';

CREATE UNIQUE INDEX PK_GNDR_TBL
	ON GNDR_TBL (
		GNDR_CD ASC
	);

ALTER TABLE GNDR_TBL
	ADD
		CONSTRAINT PK_GNDR_TBL
		PRIMARY KEY (
			GNDR_CD
		);

/* 광고 요청 테이블 */
CREATE TABLE ADVT_REQ_TBL (
	ADVT_REQ_CD NUMBER NOT NULL, /* 광고 요청 코드 */
	PROD_CD NUMBER NOT NULL, /* 상품 코드 */
	SBJCT VARCHAR2(20) NOT NULL, /* 제목 */
	STRT DATE NOT NULL, /* 시작일 */
	END DATE NOT NULL, /* 종료일 */
	CASH NUMBER NOT NULL, /* 금액 */
	IMG VARCHAR2(50) NOT NULL /* 광고 요청 이미지 */
);

COMMENT ON TABLE ADVT_REQ_TBL IS '광고 요청 테이블';

COMMENT ON COLUMN ADVT_REQ_TBL.ADVT_REQ_CD IS '광고 요청 코드';

COMMENT ON COLUMN ADVT_REQ_TBL.PROD_CD IS '상품 코드';

COMMENT ON COLUMN ADVT_REQ_TBL.SBJCT IS '제목';

COMMENT ON COLUMN ADVT_REQ_TBL.STRT IS '시작일';

COMMENT ON COLUMN ADVT_REQ_TBL.END IS '종료일';

COMMENT ON COLUMN ADVT_REQ_TBL.CASH IS '금액';

COMMENT ON COLUMN ADVT_REQ_TBL.IMG IS '광고 요청 이미지';

CREATE UNIQUE INDEX PK_ADVT_REQ_TBL
	ON ADVT_REQ_TBL (
		ADVT_REQ_CD ASC
	);

ALTER TABLE ADVT_REQ_TBL
	ADD
		CONSTRAINT PK_ADVT_REQ_TBL
		PRIMARY KEY (
			ADVT_REQ_CD
		);

/* 상품 게시 테이블 */
CREATE TABLE PROD_POST_TBL (
	PROD_POST_CD NUMBER NOT NULL, /* 상품 게시 코드 */
	STT VARCHAR2(10) NOT NULL /* 상품 게시 상태 */
);

COMMENT ON TABLE PROD_POST_TBL IS '상품 게시 테이블';

COMMENT ON COLUMN PROD_POST_TBL.PROD_POST_CD IS '상품 게시 코드';

COMMENT ON COLUMN PROD_POST_TBL.STT IS '상품 게시 상태';

CREATE UNIQUE INDEX PK_PROD_POST_TBL
	ON PROD_POST_TBL (
		PROD_POST_CD ASC
	);

ALTER TABLE PROD_POST_TBL
	ADD
		CONSTRAINT PK_PROD_POST_TBL
		PRIMARY KEY (
			PROD_POST_CD
		);

/* 회원 탈퇴 테이블 */
CREATE TABLE WTDRL_TBL (
	WTDRL_CD NUMBER NOT NULL, /* 탈퇴 코드 */
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	CTNT VARCHAR2(100) NOT NULL, /* 탈퇴 사유 */
	DT DATE NOT NULL /* 탈퇴 날짜 */
);

COMMENT ON TABLE WTDRL_TBL IS '회원 탈퇴 테이블';

COMMENT ON COLUMN WTDRL_TBL.WTDRL_CD IS '탈퇴 코드';

COMMENT ON COLUMN WTDRL_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN WTDRL_TBL.CTNT IS '탈퇴 사유';

COMMENT ON COLUMN WTDRL_TBL.DT IS '탈퇴 날짜';

CREATE UNIQUE INDEX PK_WTDRL_TBL
	ON WTDRL_TBL (
		WTDRL_CD ASC
	);

ALTER TABLE WTDRL_TBL
	ADD
		CONSTRAINT PK_WTDRL_TBL
		PRIMARY KEY (
			WTDRL_CD
		);

/* 기업 2차 경고 테이블 */
CREATE TABLE CMPNY_WAR2_TBL (
	CMPNY_ID CHAR(10) NOT NULL, /* 사업자 번호 */
	CTNT VARCHAR2(100) NOT NULL /* 경고 내용 */
);

COMMENT ON TABLE CMPNY_WAR2_TBL IS '기업 2차 경고 테이블';

COMMENT ON COLUMN CMPNY_WAR2_TBL.CMPNY_ID IS '사업자 번호';

COMMENT ON COLUMN CMPNY_WAR2_TBL.CTNT IS '경고 내용';

CREATE UNIQUE INDEX PK_CMPNY_WAR2_TBL
	ON CMPNY_WAR2_TBL (
		CMPNY_ID ASC
	);

ALTER TABLE CMPNY_WAR2_TBL
	ADD
		CONSTRAINT PK_CMPNY_WAR2_TBL
		PRIMARY KEY (
			CMPNY_ID
		);

/* 기업 3차 정지 테이블 */
CREATE TABLE CMPNY_WAR3_TBL (
	CMPNY_ID CHAR(10) NOT NULL, /* 사업자 번호 */
	CTNT VARCHAR2(100) NOT NULL /* 정지 내용 */
);

COMMENT ON TABLE CMPNY_WAR3_TBL IS '기업 3차 정지 테이블';

COMMENT ON COLUMN CMPNY_WAR3_TBL.CMPNY_ID IS '사업자 번호';

COMMENT ON COLUMN CMPNY_WAR3_TBL.CTNT IS '정지 내용';

CREATE UNIQUE INDEX PK_CMPNY_WAR3_TBL
	ON CMPNY_WAR3_TBL (
		CMPNY_ID ASC
	);

ALTER TABLE CMPNY_WAR3_TBL
	ADD
		CONSTRAINT PK_CMPNY_WAR3_TBL
		PRIMARY KEY (
			CMPNY_ID
		);

/* 회원 2차 경고 테이블 */
CREATE TABLE USR_WAR2_TBL (
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	CTNT VARCHAR2(100) NOT NULL /* 경고 내용 */
);

COMMENT ON TABLE USR_WAR2_TBL IS '회원 2차 경고 테이블';

COMMENT ON COLUMN USR_WAR2_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN USR_WAR2_TBL.CTNT IS '경고 내용';

CREATE UNIQUE INDEX PK_USR_WAR2_TBL
	ON USR_WAR2_TBL (
		USR_ID ASC
	);

ALTER TABLE USR_WAR2_TBL
	ADD
		CONSTRAINT PK_USR_WAR2_TBL
		PRIMARY KEY (
			USR_ID
		);

/* 회원 3차 경고 테이블 */
CREATE TABLE USR_WAR3_TBL (
	USR_ID VARCHAR2(20) NOT NULL, /* 회원 아이디 */
	CTNT VARCHAR2(100) NOT NULL /* 경고 내용 */
);

COMMENT ON TABLE USR_WAR3_TBL IS '회원 3차 경고 테이블';

COMMENT ON COLUMN USR_WAR3_TBL.USR_ID IS '회원 아이디';

COMMENT ON COLUMN USR_WAR3_TBL.CTNT IS '경고 내용';

CREATE UNIQUE INDEX PK_USR_WAR3_TBL
	ON USR_WAR3_TBL (
		USR_ID ASC
	);

ALTER TABLE USR_WAR3_TBL
	ADD
		CONSTRAINT PK_USR_WAR3_TBL
		PRIMARY KEY (
			USR_ID
		);

ALTER TABLE CMPNY_TBL
	ADD
		CONSTRAINT FK_CMPNY_CTGY_TBL_TO_CMPNY_TBL
		FOREIGN KEY (
			CMPNY_CTGY_ID
		)
		REFERENCES CMPNY_CTGY_TBL (
			CMPNY_CTGY_ID
		);

ALTER TABLE USR_TBL
	ADD
		CONSTRAINT FK_GNDR_TBL_TO_USR_TBL
		FOREIGN KEY (
			GNDR_CD
		)
		REFERENCES GNDR_TBL (
			GNDR_CD
		);

ALTER TABLE PROD_TBL
	ADD
		CONSTRAINT FK_CMPNY_TBL_TO_PROD_TBL
		FOREIGN KEY (
			CMPNY_ID
		)
		REFERENCES CMPNY_TBL (
			CMPNY_ID
		);

ALTER TABLE PROD_TBL
	ADD
		CONSTRAINT FK_PROD_POST_TBL_TO_PROD_TBL
		FOREIGN KEY (
			PROD_POST_CD
		)
		REFERENCES PROD_POST_TBL (
			PROD_POST_CD
		);

ALTER TABLE RSVTN_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_RSVTN_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE RSVTN_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_RSVTN_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE SEL_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_SEL_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE SEL_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_SEL_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE ADV_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_ADV_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE ADV_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_ADV_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE QUSR_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_QUSR_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE PROD_CMT_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_PROD_CMT_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE PROD_CMT_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_PROD_CMT_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE AD_CNFM_TBL
	ADD
		CONSTRAINT FK_AD_PT_TBL_TO_AD_CNFM_TBL
		FOREIGN KEY (
			AD_PT_CD
		)
		REFERENCES AD_PT_TBL (
			AD_PT_CD
		);

ALTER TABLE AD_CNFM_TBL
	ADD
		CONSTRAINT FK_PMT_TBL_TO_AD_CNFM_TBL
		FOREIGN KEY (
			PMT_CD
		)
		REFERENCES PMT_TBL (
			PMT_CD
		);

ALTER TABLE PMT_TBL
	ADD
		CONSTRAINT FK_PMT_CTGY_TBL_TO_PMT_TBL
		FOREIGN KEY (
			PMT_CTGY_CD
		)
		REFERENCES PMT_CTGY_TBL (
			PMT_CTGY_CD
		);

ALTER TABLE PMT_TBL
	ADD
		CONSTRAINT FK_ADVT_REQ_TBL_TO_PMT_TBL
		FOREIGN KEY (
			ADVT_REQ_CD
		)
		REFERENCES ADVT_REQ_TBL (
			ADVT_REQ_CD
		);

ALTER TABLE USR_WAR1_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_USR_WAR1_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE FAQ_TBL
	ADD
		CONSTRAINT FK_FAQ_CTGY_TBL_TO_FAQ_TBL
		FOREIGN KEY (
			FAQ_CTGY_CD
		)
		REFERENCES FAQ_CTGY_TBL (
			FAQ_CTGY_CD
		);

ALTER TABLE FAQ_TBL
	ADD
		CONSTRAINT FK_ADMIN_TBL_TO_FAQ_TBL
		FOREIGN KEY (
			ADMIN_CD
		)
		REFERENCES ADMIN_TBL (
			ADMIN_CD
		);

ALTER TABLE IMG_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_IMG_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE EST_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_EST_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE EST_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_EST_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE EST_TBL
	ADD
		CONSTRAINT FK_DTL_PROD_TBL_TO_EST_TBL
		FOREIGN KEY (
			DTL_PROD_CD
		)
		REFERENCES DTL_PROD_TBL (
			DTL_PROD_CD
		);

ALTER TABLE NTC_TBL
	ADD
		CONSTRAINT FK_ADMIN_TBL_TO_NTC_TBL
		FOREIGN KEY (
			ADMIN_CD
		)
		REFERENCES ADMIN_TBL (
			ADMIN_CD
		);

ALTER TABLE RVW_CMT_TBL
	ADD
		CONSTRAINT FK_PROD_CMT_TBL_TO_RVW_CMT_TBL
		FOREIGN KEY (
			PROD_CMT_CD
		)
		REFERENCES PROD_CMT_TBL (
			PROD_CMT_CD
		);

ALTER TABLE RVW_CMT_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_RVW_CMT_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE ADV_CMT_TBL
	ADD
		CONSTRAINT FK_ADV_TBL_TO_ADV_CMT_TBL
		FOREIGN KEY (
			ADV_CD
		)
		REFERENCES ADV_TBL (
			ADV_CD
		);

ALTER TABLE QCMPNY_TBL
	ADD
		CONSTRAINT FK_CMPNY_TBL_TO_QCMPNY_TBL
		FOREIGN KEY (
			CMPNY_ID
		)
		REFERENCES CMPNY_TBL (
			CMPNY_ID
		);

ALTER TABLE CMPNY_WAR1_TBL
	ADD
		CONSTRAINT FK_CMPNY_TBL_TO_CMPNY_WAR1_TBL
		FOREIGN KEY (
			CMPNY_ID
		)
		REFERENCES CMPNY_TBL (
			CMPNY_ID
		);

ALTER TABLE QAU_CMT_TBL
	ADD
		CONSTRAINT FK_QUSR_TBL_TO_QAU_CMT_TBL
		FOREIGN KEY (
			USR_QNA_CD
		)
		REFERENCES QUSR_TBL (
			USR_QNA_CD
		);

ALTER TABLE QAU_CMT_TBL
	ADD
		CONSTRAINT FK_ADMIN_TBL_TO_QAU_CMT_TBL
		FOREIGN KEY (
			ADMIN_CD
		)
		REFERENCES ADMIN_TBL (
			ADMIN_CD
		);

ALTER TABLE QAC_CMT_TBL
	ADD
		CONSTRAINT FK_ADMIN_TBL_TO_QAC_CMT_TBL
		FOREIGN KEY (
			ADMIN_CD
		)
		REFERENCES ADMIN_TBL (
			ADMIN_CD
		);

ALTER TABLE QAC_CMT_TBL
	ADD
		CONSTRAINT FK_QCMPNY_TBL_TO_QAC_CMT_TBL
		FOREIGN KEY (
			CMPNY_QNA_CD
		)
		REFERENCES QCMPNY_TBL (
			CMPNY_QNA_CD
		);

ALTER TABLE VW_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_VW_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE VW_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_VW_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE DTL_PROD_TBL
	ADD
		CONSTRAINT FK_CMPNY_TBL_TO_DTL_PROD_TBL
		FOREIGN KEY (
			CMPNY_ID
		)
		REFERENCES CMPNY_TBL (
			CMPNY_ID
		);

ALTER TABLE ADVT_REQ_TBL
	ADD
		CONSTRAINT FK_PROD_TBL_TO_ADVT_REQ_TBL
		FOREIGN KEY (
			PROD_CD
		)
		REFERENCES PROD_TBL (
			PROD_CD
		);

ALTER TABLE WTDRL_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_WTDRL_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE CMPNY_WAR2_TBL
	ADD
		CONSTRAINT FK_CMPNY_TBL_TO_CMPNY_WAR2_TBL
		FOREIGN KEY (
			CMPNY_ID
		)
		REFERENCES CMPNY_TBL (
			CMPNY_ID
		);

ALTER TABLE CMPNY_WAR3_TBL
	ADD
		CONSTRAINT FK_CMPNY_TBL_TO_CMPNY_WAR3_TBL
		FOREIGN KEY (
			CMPNY_ID
		)
		REFERENCES CMPNY_TBL (
			CMPNY_ID
		);

ALTER TABLE USR_WAR2_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_USR_WAR2_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE USR_WAR3_TBL
	ADD
		CONSTRAINT FK_USR_TBL_TO_USR_WAR3_TBL
		FOREIGN KEY (
			USR_ID
		)
		REFERENCES USR_TBL (
			USR_ID
		);

ALTER TABLE CMPNY_TBL
DROP COLUMN WTDRL;


ALTER TABLE CMPNY_TBL
ADD (WTDRL CHAR(1) DEFAULT 'N');
