/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-08-04 04:58:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.StudyRoom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class StudyRoomCreate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1468241066457L));
    _jspx_dependants.put("jar:file:/C:/sistproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/StudyProject/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   String cp = request.getContextPath();
   // 확인
   //System.out.println(cp);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>글쓰기</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"http://bootswatch.com/paper/bootstrap.min.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://bootswatch.com/paper/bootstrap.css\" > -->\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Preloader -->\r\n");
      out.write("<!--     <link rel=\"stylesheet\" href=\"css/preloader.css\" type=\"text/css\" media=\"screen, print\"/> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.css\">\r\n");
      out.write("    <!-- Animate CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Style -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Responsive CSS -->\r\n");
      out.write("    <!-- <link href=\"css/responsive.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"js/lte-ie7.js\"></script>\r\n");
      out.write("     <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("     <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("   <![endif]-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"ajax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(cp );
      out.write("/js/HuskyEZCreator.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/* \r\n");
      out.write("\t지도 팝업창 불러오기\r\n");
      out.write("\t$(document).ready(function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$(\"#map\").click(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twinObj = window.open('StudyRoomCreateMap.room','지도','width=400,height=550,left=150,top=150');\r\n");
      out.write("\t\t\talert(winObj.document.forms.map1.latlng.value = latlng);\r\n");
      out.write("\t\t\twinObj.document.forms.map1.latlng.value = latlng;\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("   var oEditors = [];\r\n");
      out.write("   $(function()\r\n");
      out.write("         {\r\n");
      out.write("\r\n");
      out.write("            nhn.husky.EZCreator.createInIFrame({\r\n");
      out.write("             oAppRef: oEditors,\r\n");
      out.write("             elPlaceHolder: \"ir1\", //textarea에서 지정한 id와 일치해야 합니다. \r\n");
      out.write("             sSkinURI: \"/StudyProject/SE2/SmartEditor2Skin.html\",  \r\n");
      out.write("             htParams : {\r\n");
      out.write("                 // 툴바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("                 bUseToolbar : true,             \r\n");
      out.write("\r\n");
      out.write("                 // 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("                 bUseVerticalResizer : true,     \r\n");
      out.write("\r\n");
      out.write("                 // 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("                 bUseModeChanger : true,         \r\n");
      out.write("                 fOnBeforeUnload : function(){\r\n");
      out.write("                 }\r\n");
      out.write("             }, \r\n");
      out.write("             fOnAppLoad : function()\r\n");
      out.write("             {\r\n");
      out.write("                 //기존 저장된 내용의 text 내용을 에디터상에 뿌려주고자 할때 사용\r\n");
      out.write("                 //oEditors.getById[\"ir1\"].exec(\"PASTE_HTML\", [\"내용을 입력하세요. <br>(내용을 지우고 입력하시기 바랍니다.)\"]);\r\n");
      out.write("            \t \r\n");
      out.write("             },\r\n");
      out.write("             fCreator: \"createSEditor2\"\r\n");
      out.write("         });      \r\n");
      out.write("\r\n");
      out.write("           //저장버튼 클릭시 form 전송\r\n");
      out.write("           $(\"#save\").click(function()\r\n");
      out.write("           {\r\n");
      out.write("               // 데이터 검사(누락된 입력값 검사) 후 submit 액션\r\n");
      out.write("               if($(\"#title\").val()=='')            \r\n");
      out.write("               {\r\n");
      out.write("                  //$(\"#errMsg\").css(\"display\",\"inline\")\r\n");
      out.write("                  alert(\"방 이름을 입력해주세요.\");\r\n");
      out.write("                  $(\"#title\").focus();\r\n");
      out.write("               }\r\n");
      out.write("               else if($('#price').val()=='0')            \r\n");
      out.write("               {\r\n");
      out.write("                  alert(\"가격을 입력해주세요.\");\r\n");
      out.write("                  $(\"#price\").focus();\r\n");
      out.write("               }\r\n");
      out.write("               else if($(\"#inwon\").val()=='0')            \r\n");
      out.write("               {\r\n");
      out.write("                  alert(\"수용인원을 입력해주세요.\");\r\n");
      out.write("                  $(\"#inwon\").focus();\r\n");
      out.write("               }\r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("/*             else if($(\"#ir1\").val()==\"\")            \r\n");
      out.write("               {\r\n");
      out.write("                  alert(\"내용을 입력해 주세요.\");\r\n");
      out.write("                  $(\"#ir1\").focus();\r\n");
      out.write("               } */\r\n");
      out.write("             \r\n");
      out.write("               \r\n");
      out.write("               //저장버튼 클릭시 form 전송\r\n");
      out.write("               else \r\n");
      out.write("               {\r\n");
      out.write("              \t oEditors.getById[\"ir1\"].exec(\"UPDATE_CONTENTS_FIELD\", []);\r\n");
      out.write("                   $(\"#frm\").submit();\r\n");
      out.write("               }\r\n");
      out.write("               \r\n");
      out.write("           });  \r\n");
      out.write("\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("   <div class=\"form-group col-sm-2\"></div>\r\n");
      out.write("   <div class=\"form-group col-sm-8 form-group-sm\">\r\n");
      out.write("            \r\n");
      out.write("      <form id=\"frm\" action=\"StudyRoomInsert.room\" method=\"post\" >\r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"form-group\">\r\n");
      out.write("            \r\n");
      out.write("                     <label class=\"col-sm-2 text-right\">방이름</label> \r\n");
      out.write("                     <div class=\"col-sm-9\">\r\n");
      out.write("                           <input type=\"text\" id=\"title\" name=\"title\" class=\"form-control\" placeholder=\"방 제목을 입력하세요\"/>\r\n");
      out.write("                           <!-- 지도 좌표 찍기\r\n");
      out.write("                                아래 text 박스 안에 지도 클릭 시 좌표가 나옴, hidden 속성 없에야 보임.   \r\n");
      out.write("                            -->   \r\n");
      out.write("                    <!--        \r\n");
      out.write("                  \t\t지도 팝업창 불러오기\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-success btn-sm\" type=\"button\" id=\"map\">주소 검색<i class=\"fa fa-edit spaceLeft\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("                    -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("      \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">지역</label> \r\n");
      out.write("               <div class=\"col-sm-9\">   \r\n");
      out.write("                  <select name=\"location\" class=\"form-control\">\r\n");
      out.write("                     <option value=\"1\">서울</option>\r\n");
      out.write("                     <option value=\"2\">경기</option>\r\n");
      out.write("                     <option value=\"3\">인천</option>\r\n");
      out.write("                     <option value=\"4\">충청북도</option>\r\n");
      out.write("                     <option value=\"5\">충청남도</option>\r\n");
      out.write("                     <option value=\"6\">전라북도</option>\r\n");
      out.write("                     <option value=\"7\">전라남도</option>\r\n");
      out.write("                     <option value=\"8\">강원도</option>\r\n");
      out.write("                     <option value=\"9\">경상남도</option>\r\n");
      out.write("                     <option value=\"10\">경상북도</option>\r\n");
      out.write("                     <option value=\"11\">제주도</option>   \r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">업체명</label>\r\n");
      out.write("               <div class=\"col-sm-9\">   \r\n");
      out.write("                  <select name=\"shopId\" class=\"form-control\">\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("                     \r\n");
      out.write("                  </select>                  \r\n");
      out.write("               </div>\r\n");
      out.write("            </div> \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">시간/일</label>\r\n");
      out.write("               <div class=\"col-sm-3 text-right\">\r\n");
      out.write("                  <input type=\"radio\" value=\"2\" name=\"timeCheck\" checked=\"checked\">시간\r\n");
      out.write("                  &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                  <input type=\"radio\" value=\"1\" name=\"timeCheck\">일\r\n");
      out.write("               </div>\r\n");
      out.write("               <label class=\"col-sm-3 text-right\">가&nbsp;격</label>\r\n");
      out.write("               <div class=\"col-sm-3 text-right\">\r\n");
      out.write("                  <input type=\"text\" id=\"price\" name=\"price\" class=\"form-control\" onkeyPress=\"if ((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\" maxlength=10 value=\"0\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">수용인원</label>\r\n");
      out.write("               <div class=\"col-sm-9\">\r\n");
      out.write("                  <input type=\"text\" name=\"inwon\" id=\"inwon\" placeholder=\"0\" value=\"0\" class=\"form-control\"></div>            \r\n");
      out.write("               </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">최소이용시간</label>\r\n");
      out.write("               \r\n");
      out.write("               <div class=\"col-sm-9\"><select name=\"minTime\" class=\"form-control\">\r\n");
      out.write("                     <option value=\"1\">1시간</option>\r\n");
      out.write("                     <option value=\"2\">2시간</option>\r\n");
      out.write("                     <option value=\"3\">3시간</option>\r\n");
      out.write("                     <option value=\"4\">4시간</option>\r\n");
      out.write("                     <option value=\"5\">5시간</option>\r\n");
      out.write("                     <option value=\"6\">6시간</option>\r\n");
      out.write("                     <option value=\"7\">7시간</option>\r\n");
      out.write("                     <option value=\"8\">8시간</option>\r\n");
      out.write("                     <option value=\"9\">9시간</option>\r\n");
      out.write("                     <option value=\"10\">10시간</option>\r\n");
      out.write("                     <option value=\"11\">영업시간동안</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">콘센트</label>\r\n");
      out.write("         \r\n");
      out.write("               <div class=\"col-sm-9\"><select name=\"consent\" class=\"form-control\">\r\n");
      out.write("                     <option value=\"9\">없음</option>\r\n");
      out.write("                     <option value=\"1\">1개</option>\r\n");
      out.write("                     <option value=\"2\">2개</option>\r\n");
      out.write("                     <option value=\"3\">3개</option>\r\n");
      out.write("                     <option value=\"4\">4개</option>\r\n");
      out.write("                     <option value=\"5\">5개</option>\r\n");
      out.write("                     <option value=\"6\">6개</option>\r\n");
      out.write("                     <option value=\"7\">7개</option>\r\n");
      out.write("                     <option value=\"8\">8개</option>\r\n");
      out.write("                     \r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">방음상태</label>\r\n");
      out.write("               <div class=\"col-sm-9\"> \r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-sm-4\"><input type=\"radio\" value=\"1\" name=\"noiseCheck\" checked=\"checked\">안들림</div>\r\n");
      out.write("                  <div class=\"col-sm-4\"><input type=\"radio\" value=\"2\" name=\"noiseCheck\">속삭이는 정도</div>\r\n");
      out.write("                  <div class=\"col-sm-4\"><input type=\"radio\" value=\"3\" name=\"noiseCheck\">정확히 들림</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">WIFI</label>\r\n");
      out.write("               <div class=\"col-sm-9\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-sm-2\"><input type=\"radio\" value=\"1\" name=\"wifiCheck\" checked=\"checked\">최상</div>\r\n");
      out.write("                  <div class=\"col-sm-2\"><input type=\"radio\" value=\"2\" name=\"wifiCheck\">좋음</div>\r\n");
      out.write("                  <div class=\"col-sm-2\"><input type=\"radio\" value=\"3\" name=\"wifiCheck\">보통</div>\r\n");
      out.write("                  <div class=\"col-sm-2\"><input type=\"radio\" value=\"4\" name=\"wifiCheck\">나쁨</div>\r\n");
      out.write("                  <div class=\"col-sm-2\"><input type=\"radio\" value=\"5\" name=\"wifiCheck\">없음</div>\r\n");
      out.write("                  <div class=\"col-sm-2\"></div>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-sm-3\"></div>\r\n");
      out.write("               <div class=\"col-sm-3\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label class=\"col-sm-2 text-right\">냉난방기 유무</label>\r\n");
      out.write("               <div class=\"col-sm-9\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-sm-4\"><input type=\"radio\" value=\"1\" name=\"yesnoCheck\" checked=\"checked\">있음</div>\r\n");
      out.write("                  <div class=\"col-sm-4\"><input type=\"radio\" value=\"2\" name=\"yesnoCheck\">없음</div>\r\n");
      out.write("                  <div class=\"col-sm-4\"><input type=\"radio\" value=\"3\" name=\"yesnoCheck\">고장</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>      \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               \r\n");
      out.write("               <div class=\"col-sm-12\">\r\n");
      out.write("               <br>\r\n");
      out.write("                  <textarea rows=\"10\" id=\"ir1\" name=\"content\" style=\"width:720px; height:350px; \"></textarea>               \r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-sm-12 text-center\">\r\n");
      out.write("               <br><br>\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-primary\" id=\"save\">글쓰기</button>\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-default\" onclick=\"window.history.back();\">취소</button>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("   <div class=\"col-sm-2\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("   <div class=\"col-md-8\"></div>\r\n");
      out.write("   <div class=\"form-group col-md-4\">\r\n");
      out.write("   \t\t<!-- <button type=\"button\" class=\"btn btn-default cs-btn\"  onclick=\"location.href='StudyRoomMain.room'\">목록으로</button> -->\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- 좌표 찍는 값 -->\r\n");
      out.write("   <input type=\"hidden\" id=\"p_id\" name=\"bukwi\" value=\"\" >\r\n");
      out.write("   <input type=\"hidden\" id=\"t_id\" name=\"dong\" value=\"\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("   <div>");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    ");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(141,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nickname eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      <div class=\"row\">\r\n");
        out.write("         <div class=\"form-group col-xs-12\">\r\n");
        out.write("            <div class=\"\">\r\n");
        out.write("               ");
        if (_jspx_meth_c_005fimport_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("            </div>\r\n");
        out.write("         </div>\r\n");
        out.write("      </div>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(145,15) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("StudyRoomTop.jsp");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(150,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nickname ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("   <div class=\"row\">\r\n");
        out.write("      <div class=\"form-group col-xs-12\">\r\n");
        out.write("         <div class=\"\">\r\n");
        out.write("            ");
        if (_jspx_meth_c_005fimport_005f1(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("         </div>\r\n");
        out.write("      </div>\r\n");
        out.write("   </div>\r\n");
        out.write("   ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(154,12) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f1.setUrl("StudyRoomTop_member.jsp");
    int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
      if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(213,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("shop");
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(213,18) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                     ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(214,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopId==shop.shopId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" selected=\"selected\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop.shopName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f2.setParent(null);
    // /WEB-INF/jsp/StudyRoom/StudyRoomCreate.jsp(346,8) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f2.setUrl("/WEB-INF/jsp/import/copyright.jsp");
    int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
      if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
    }
    return false;
  }
}
