ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';

-- 결제 내역 뷰
CREATE OR REPLACE VIEW CMPNY_PMT_LIST_VIEW
AS
(
SELECT C.CMPNY_ID AS 사업자번호, AR.SBJCT AS 광고제목, PM.DT AS 결제일, AR.STRT AS 시작일, AR.END AS 종료일, AR.CASH AS 금액, PC.NAME AS 결제수단
FROM CMPNY_TBL C, PROD_TBL PR, ADVT_REQ_TBL AR, PMT_TBL PM, PMT_CTGY_TBL PC
WHERE C.CMPNY_ID = PR.CMPNY_ID AND PR.PROD_CD = AR.PROD_CD AND AR.ADVT_REQ_CD = PM.ADVT_REQ_CD
);

COMMENT ON TABLE CMPNY_PMT_LIST_VIEW IS '강사정보 뷰';

--SELECT * 
--FROM PMT_LIST_VIEW;

-- 기업 Q&A 뷰
CREATE OR REPLACE VIEW CMPNY_QCMPNY_VIEW
AS
(
SELECT C.CMPNY_ID AS 사업자번호, Q.SBJCT AS 제목, Q.DT AS 작성일,  Q.CNT AS 조회수
FROM CMPNY_TBL C, QCMPNY_TBL Q
WHERE C.CMPNY_ID = Q.CMPNY_ID
);

COMMENT ON TABLE CMPNY_QCMPNY_VIEW IS '기업QnA 뷰';

--SELECT *
--FROM QCMPNY_VIEW;


-- 공지사항 뷰
CREATE OR REPLACE VIEW CMPNY_NTC_VIEW
AS
(
SELECT SBJCT AS 제목, DT AS 작성일, CNT AS 조회수
FROM NTC_TBL
);

COMMENT ON TABLE CMPNY_NTC_VIEW IS '공지사항 뷰';


-- 예약 관리 뷰
CREATE OR REPLACE VIEW CMPNY_RSVTN_VIEW
AS
(
SELECT P.LIST, U.USR_ID, U.NAME, G.CTNT AS GCTNT, U.TEL, RSV.DAY, RSV.VST, RSV.INQY, RSV.RSVTN_CD, RST.CTNT AS RCTNT, C.CMPNY_ID
FROM USR_TBL U, GNDR_TBL G, RSVTN_TBL RSV, RST_TBL RST, (SELECT CASE WHEN STRT IS NULL THEN '일반'
            WHEN STRT IS NOT NULL THEN '할인'
            ELSE '알 수 없음'
       END AS "LIST"
      ,PROD_CD, CMPNY_ID
FROM PROD_TBL) P, CMPNY_TBL C
WHERE U.GNDR_CD = G.GNDR_CD AND U.USR_ID = RSV.USR_ID AND RSV.RST_CD = RST.RST_CD AND RSV.PROD_CD = P.PROD_CD AND P.CMPNY_ID = C.CMPNY_ID
);

COMMENT ON TABLE CMPNY_RSVTN_VIEW IS '예약관리 뷰';

SELECT LIST, NAME, GCTNT, TEL, DAY, VST, INQY, RCTNT, CMPNY_ID
FROM CMPNY_RSVTN_VIEW;




-- 상담 관리 뷰
CREATE OR REPLACE VIEW CMPNY_ADV_VIEW
AS
(
SELECT U.NAME, P.LIST, G.CTNT AS GCTNT, A.DT, A.CTNT, RST.CTNT AS RCTNT, A.ADV_CD, C.CMPNY_ID
FROM USR_TBL U, GNDR_TBL G, ADV_TBL A, RST_TBL RST, (SELECT PROD_CD, CMPNY_ID, CASE WHEN STRT IS NULL THEN '일반'
            WHEN STRT IS NOT NULL THEN '할인'
            ELSE '알 수 없음'
       END AS "LIST"
FROM PROD_TBL) P, CMPNY_TBL C
WHERE U.GNDR_CD = G.GNDR_CD AND U.USR_ID = A.USR_ID AND A.RST_CD = RST.RST_CD AND A.PROD_CD = P.PROD_CD AND P.CMPNY_ID = C.CMPNY_ID
);

COMMENT ON TABLE CMPNY_ADV_VIEW IS '상담관리 뷰';

SELECT NAME, LIST, GCTNT, DT, CTNT, RCTNT, ADV_CD
FROM CMPNY_ADV_VIEW;


-- 상품평 관리 뷰
CREATE OR REPLACE VIEW CMPNY_PROD_CMT_VIEW
AS
(
SELECT P.LIST, U.NAME, PC.SCR, G.CTNT AS GCTNT, PC.DT, PC.CTNT, RST.CTNT AS RCTNT, C.CMPNY_ID, RST.RST_CD, PC.PROD_CMT_CD
FROM USR_TBL U, GNDR_TBL G, PROD_CMT_TBL PC, RST_TBL RST, (SELECT PROD_CD, CMPNY_ID, CASE WHEN STRT IS NULL THEN '일반'
            WHEN STRT IS NOT NULL THEN '할인'
            ELSE '알 수 없음'
       END AS "LIST"
FROM PROD_TBL) P, CMPNY_TBL C 
WHERE U.GNDR_CD = G.GNDR_CD AND U.USR_ID = PC.USR_ID AND PC.RST_CD = RST.RST_CD AND PC.PROD_CD = P.PROD_CD AND P.CMPNY_ID = C.CMPNY_ID
);

COMMENT ON TABLE CMPNY_PROD_CMT_VIEW IS '상품평관리 뷰';

SELECT LIST, NAME, SCR, GCTNT, DT, CTNT, RCTNT, CMPNY_ID, RST_CD, PROD_CMT_CD
FROM CMPNY_PROD_CMT_VIEW;


-- 기업 FAQ 뷰
CREATE OR REPLACE VIEW CMPNY_CFAQ_VIEW
AS
(
SELECT SBJCT AS 제목, F.DT AS 작성일, F.CNT AS 조회수
FROM FAQ_TBL F, CHK_TBL C
WHERE F.CHK_CD = C.CHK_CD AND C.CTNT='기업'
);

COMMENT ON TABLE CMPNY_CFAQ_VIEW IS '기업FAQ 뷰';

--SELECT *
--FROM CFAQ_VIEW;

-- 견적 뷰
CREATE OR REPLACE VIEW CMPNY_EST_VIEW
AS
(
SELECT U.NAME, U.TEL, R.INQY, E.PRC, C.CMPNY_ID, P.NAME AS PRODUCKNAME
FROM USR_TBL U, EST_TBL E, RSVTN_TBL R, PROD_TBL P, CMPNY_TBL C
WHERE U.USR_ID = E.USR_ID AND U.USR_ID = R.USR_ID AND P.PROD_CD = E.PROD_CD AND C.CMPNY_ID = P.CMPNY_ID
);

COMMENT ON TABLE CMPNY_EST_VIEW IS '견적 뷰';

SELECT NAME, TEL, INQY, PRC
FROM CMPNY_EST_VIEW;
WHERE NAME = ? AND TEL = ?;


select *
from est_tbl;






-- 기업 메인화면 뷰
-- 경고 누적을 알려주기 위한 목적
CREATE OR REPLACE VIEW CMPNY_MAIN_WAR_VIEW
AS
(
SELECT CMPNY_ID, WAR1+WAR2+WAR3 AS WAR
FROM
(
SELECT C.CMPNY_ID, CASE WHEN CW1.CTNT IS NULL THEN '0'
            WHEN CW1.CTNT IS NOT NULL THEN '1'
            ELSE 'error'
       END AS WAR1,
       CASE WHEN CW2.CTNT IS NULL THEN '0'
            WHEN CW2.CTNT IS NOT NULL THEN '1'
            ELSE 'error'
       END AS WAR2,
       CASE WHEN CW3.CTNT IS NULL THEN '0'
            WHEN CW3.CTNT IS NOT NULL THEN '1'
            ELSE 'error'
       END AS WAR3
FROM CMPNY_TBL C, CMPNY_WAR1_TBL CW1, CMPNY_WAR2_TBL CW2, CMPNY_WAR3_TBL CW3
WHERE C.CMPNY_ID = CW1.CMPNY_ID(+) AND C.CMPNY_ID = CW2.CMPNY_ID(+) AND C.CMPNY_ID = CW3.CMPNY_ID(+)
)
);

COMMENT ON TABLE CMPNY_MAIN_WAR_VIEW IS '기업경고 뷰';

SELECT WAR FROM CMPNY_MAIN_WAR_VIEW WHERE CMPNY_ID = '1111111111';

-- 기업메인공지 뷰
CREATE OR REPLACE VIEW CMPNY_MAIN_NTC_VIEW
AS
(
SELECT N.SBJCT
FROM 
(
SELECT MAX(NTC_CD) AS MAX
FROM NTC_TBL
) T, NTC_TBL N
WHERE N.NTC_CD > (T.MAX - 5)
);

COMMENT ON TABLE CMPNY_MAIN_NTC_VIEW IS '기업메인공지 뷰';



SELECT COUNT(*) AS TODAY
FROM CMPNY_RSVTN_VIEW
WHERE VST = SYSDATE;


-- 기업 메인화면 금일 주요일정 예약 갯수 체크
CREATE OR REPLACE VIEW CMPNY_MAIN_RSVTN_VIEW
AS
(
SELECT CMPNY_ID
FROM CMPNY_RSVTN_VIEW
WHERE (RCTNT = '대기') AND (VST >= SYSDATE AND VST < (SYSDATE + 1))
);

COMMENT ON TABLE CMPNY_MAIN_RSVTN_VIEW IS '기업메인금일예약 뷰';


-- 기업 메인화면 금일 주요일정 상담 갯수 체크
CREATE OR REPLACE VIEW CMPNY_MAIN_ADV_VIEW
AS
(
SELECT CMPNY_ID
FROM CMPNY_ADV_VIEW
WHERE (RCTNT = '대기') AND (DT >= SYSDATE AND DT < (SYSDATE + 1))
);


COMMENT ON TABLE CMPNY_MAIN_ADV_VIEW IS '기업메인금일상담 뷰';


-- 기업 메인화면 금일 주요일정 상품평 갯수 체크
CREATE OR REPLACE VIEW CMPNY_MAIN_REVIEW_VIEW
AS
(
SELECT CMPNY_ID
FROM CMPNY_PROD_CMT_VIEW
WHERE (RCTNT = '대기') AND (DT >= SYSDATE AND DT < (SYSDATE + 1))
);


COMMENT ON TABLE CMPNY_MAIN_ADV_VIEW IS '기업메인금일상품평 뷰';

-- 일반 상품 이미지
SELECT C.CMPNY_ID, IMG
FROM CMPNY_TBL C, PROD_TBL P
WHERE C.CMPNY_ID = P.CMPNY_ID
AND STRT IS NULL
AND C.CMPNY_ID='1111111111';

-- 할인 상품 이미지
SELECT C.CMPNY_ID, IMG
FROM CMPNY_TBL C, PROD_TBL P
WHERE C.CMPNY_ID = P.CMPNY_ID
AND STRT IS NOT NULL;

-- 광고 상품 이미지
SELECT C.CMPNY_ID, A.IMG AS IMG
FROM CMPNY_TBL C, PROD_TBL P, ADVT_REQ_TBL A
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = A.PROD_CD
AND C.CMPNY_ID = '1111111111';




-- 일반 상품 방문자수

SELECT COUNT(C.CMPNY_ID) AS COUNT
FROM CMPNY_TBL C, PROD_TBL P, VW_TBL V
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = V.PROD_CD
AND STRT IS NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1)
AND C.CMPNY_ID = '1111111111';


-- 할인상품 방문자수

SELECT COUNT(C.CMPNY_ID) AS COUNT
FROM CMPNY_TBL C, PROD_TBL P, VW_TBL V
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = V.PROD_CD
AND STRT IS NOT NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1)
AND C.CMPNY_ID = '1111111111';


-- 당일 일반 상품 예약 신청

SELECT COUNT(C.CMPNY_ID) AS COUNT
FROM CMPNY_TBL C, PROD_TBL P, RSVTN_TBL R
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = R.PROD_CD
AND STRT IS NULL
AND (DAY >= SYSDATE AND DAY < SYSDATE + 1);


-- 당일 할인 상품 예약 신청
SELECT COUNT(C.CMPNY_ID) AS COUNT
FROM CMPNY_TBL C, PROD_TBL P, RSVTN_TBL R
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = R.PROD_CD
AND STRT IS NOT NULL
AND (DAY >= SYSDATE AND DAY < SYSDATE + 1);






-- 당일 일반 상품 상담 신청

SELECT COUNT(C.CMPNY_ID) AS COUNT
FROM CMPNY_TBL C, PROD_TBL P, ADV_TBL A
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = A.PROD_CD
AND STRT IS NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1);


-- 당일 할인 상품 상담 신청
SELECT COUNT(C.CMPNY_ID) AS COUNT
FROM CMPNY_TBL C, PROD_TBL P, ADV_TBL A
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = A.PROD_CD
AND STRT IS NOT NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1);


/*
-- 당일 일반 상품 상품평 신청
SELECT COUNT(CMPNY_ID) AS COUNT 
FROM 
(
SELECT C.CMPNY_ID, P.STRT, PC.DT
FROM CMPNY_TBL C, PROD_TBL P, PROD_CMT_TBL PC
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = PC.PROD_CD
)
WHERE STRT IS NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1);


-- 당일 할인 상품 상품평 신청
SELECT COUNT(CMPNY_ID) AS COUNT 
FROM 
(
SELECT C.CMPNY_ID, P.STRT, PC.DT
FROM CMPNY_TBL C, PROD_TBL P, PROD_CMT_TBL PC
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = PC.PROD_CD
)
WHERE STRT IS NOT NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1);
*/



-- 당일 일반 상품 상품평 신청
SELECT COUNT(CMPNY_ID) AS COUNT, NVL(TRUNC(AVG(SCR), 1), 0) AS AVG
FROM
(
SELECT C.CMPNY_ID, P.STRT, PC.DT, PC.SCR
FROM CMPNY_TBL C, PROD_TBL P, PROD_CMT_TBL PC
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = PC.PROD_CD
)
WHERE STRT IS NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1)
AND CMPNY_ID = '1111111111';


-- 당일 할인 상품 상품평 신청
SELECT COUNT(CMPNY_ID) AS COUNT, NVL(TRUNC(AVG(SCR), 1), 0) AS AVG
FROM
(
SELECT C.CMPNY_ID, P.STRT, PC.DT, PC.SCR
FROM CMPNY_TBL C, PROD_TBL P, PROD_CMT_TBL PC
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = PC.PROD_CD
)
WHERE STRT IS NOT NULL
AND (DT >= SYSDATE AND DT < SYSDATE + 1);


 
 
 
 
--일반 상품 대표 이미지 필요
SELECT C.CMPNY_ID, PR.NAME, PO.STT 
FROM CMPNY_TBL C, PROD_TBL PR, POST_TBL PO
WHERE C.CMPNY_ID = PR.CMPNY_ID
AND PO.POST_CD = PR.POST_CD
AND PR.STRT IS NULL;






--할인 상품 대표 이미지 필요
SELECT C.CMPNY_ID, PR.NAME, PO.STT 
FROM CMPNY_TBL C, PROD_TBL PR, POST_TBL PO
WHERE C.CMPNY_ID = PR.CMPNY_ID
AND PO.POST_CD = PR.POST_CD
AND PR.STRT IS NOT NULL;



-- 광고 상품 관리 입장 뷰
SELECT C.CMPNY_ID, A.SBJCT, ROUND(A.END - SYSDATE) AS DDAY, A.IMG
FROM CMPNY_TBL C, PROD_TBL P, ADVT_REQ_TBL A
WHERE C.CMPNY_ID = P.CMPNY_ID
AND P.PROD_CD = A.PROD_CD;




-- 상품관리 - 일반 영역
CREATE OR REPLACE VIEW CMPNY_NORMAL_PRO_VIEW
AS
(
SELECT C.CMPNY_ID, P.IMG, P.NAME, PO.STT
FROM CMPNY_TBL C, PROD_TBL P, POST_TBL PO
WHERE C.CMPNY_ID = P.CMPNY_ID
AND PO.POST_CD = P.POST_CD
AND STRT IS NULL
);
COMMENT ON TABLE CMPNY_NORMAL_PRO_VIEW IS '기업일반상품등록뷰';


-- 상품관리 - 할인 영역
CREATE OR REPLACE VIEW CMPNY_DISCOUNT_PRO_VIEW
AS
(
SELECT C.CMPNY_ID, P.IMG, P.NAME, PO.STT
FROM CMPNY_TBL C, PROD_TBL P, POST_TBL PO
WHERE C.CMPNY_ID = P.CMPNY_ID
AND PO.POST_CD = P.POST_CD
AND STRT IS NOT NULL
);
COMMENT ON TABLE CMPNY_DISCOUNT_PRO_VIEW IS '기업할인상품등록뷰';

-- 상품관리 - 광고 영역
CREATE OR REPLACE VIEW CMPNY_ADVT_PRO_VIEW
AS
(
SELECT C.CMPNY_ID, A.IMG, A.SBJCT, A.END, PO.STT
FROM CMPNY_TBL C, PROD_TBL PR, ADVT_REQ_TBL A, PMT_TBL PM, AD_CNFM_TBL AD, POST_TBL PO
WHERE C.CMPNY_ID = PR.CMPNY_ID
AND PR.PROD_CD = A.PROD_CD
AND A.ADVT_REQ_CD = PM.ADVT_REQ_CD
AND PM.PMT_CD = AD.PMT_CD
AND PO.POST_CD = AD.POST_CD
AND PR.STRT IS NULL
);

COMMENT ON TABLE CMPNY_ADVT_PRO_VIEW IS '기업광고상품등록뷰';





-- 기업 상품 전체 뷰
CREATE OR REPLACE VIEW CMPNY_PRO_ALL_VIEW
AS
(
SELECT CC.NAME AS CCNAME, C.HMPG, C.CMPNY_ID, P.NAME AS PNAME, PT.NAME AS PTNAME, D.NAME AS DPNAME, D.PRC, I.PTH
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT, DTL_PROD_TBL D, IMG_TBL I
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
AND P.PROD_CD = PT.PROD_CD
AND PT.PROD_TP_CD = D.PROD_TP_CD
AND D.DTL_PROD_CD = I.DTL_PROD_CD
);

COMMENT ON TABLE CMPNY_ADVT_PRO_VIEW IS '기업상품전체뷰';


-- 기업 상품 소카테고리 뷰
CREATE OR REPLACE VIEW CMPNY_PRO_SMALLCTR_VIEW
AS
(
SELECT CC.NAME AS CCNAME, C.HMPG, C.CMPNY_ID, P.NAME AS PNAME, PT.NAME AS PTNAME, D.NAME AS DPNAME, D.PRC
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT, DTL_PROD_TBL D
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
AND P.PROD_CD = PT.PROD_CD
AND PT.PROD_TP_CD = D.PROD_TP_CD
);

COMMENT ON TABLE CMPNY_PRO_SMALLCTR_VIEW IS '기업상품소카테고리뷰';


-- 기업 상품 대카테고리 뷰
CREATE OR REPLACE VIEW CMPNY_PRO_BIGCTR_VIEW
AS
(
SELECT CC.NAME AS CCNAME, C.HMPG, C.CMPNY_ID, P.NAME AS PNAME, PT.NAME AS PTNAME
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
AND P.PROD_CD = PT.PROD_CD
);

COMMENT ON TABLE CMPNY_PRO_BIGCTR_VIEW IS '기업상품대카테고리뷰';


-- 기업 상품 대카테고리 뷰
CREATE OR REPLACE VIEW CMPNY_PRO_INFO_VIEW
AS
(
SELECT CC.NAME AS CCNAME, C.HMPG, C.ADDR1||C.ADDR2 AS ADDR, C.CMPNY_ID, P.NAME AS PNAME, P.IMG
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
);

COMMENT ON TABLE CMPNY_PRO_INFO_VIEW IS '기업상품기업정보뷰';










/*
CREATE OR REPLACE VIEW CMPNY_TBL_VIEW
AS
SELECT A.CMPNY_ID, B.NAME AS CMPNY, A.NAME, A.CTNT, A.PWD, A.EMAIL, A.TEL, A.HMPG, A.ADDR_NO, A.ADDR1, A.ADDR2, A.WTDRL
FROM CMPNY_TBL A, CMPNY_CTGY_TBL B
WHERE A.CMPNY_CTGY_ID = B.CMPNY_CTGY_ID;



CREATE OR REPLACE VIEW USR_TBL_VIEW
AS
SELECT A.USR_ID,B.CTNT,A.NAME,A.PWD, A.EMAIL, A.TEL, A.BRTHDAY, A.ADDR_NO, A.ADDR1, A.ADDR2
FROM USR_TBL A, GNDR_TBL B
WHERE A.GNDR_CD = B.GNDR_CD;
*/