/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-07-18 03:55:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1465350034000L));
    _jspx_dependants.put("jar:file:/C:/sistproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.print(cp );
      out.write("/css/hyuncss/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(cp );
      out.write("/css/hyuncss/main.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(cp );
      out.write("/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(cp );
      out.write("/js/mainjs/jquery.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(cp );
      out.write("/js/mainjs/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function()\r\n");
      out.write("{\t\t\r\n");
      out.write("\t$('#userloginaction').css(\"display\",\"block\");//일반회원 디스플레이block\r\n");
      out.write("\t$('#cmpnyloginaction').css(\"display\",\"none\");//기업회원 디스플레이none\r\n");
      out.write("\t$('#adminloginaction').css(\"display\",\"none\");//관리자 디스플레이none\r\n");
      out.write("\t\r\n");
      out.write("\t$('#search_id').click(function(){//아이디찾기를 눌렀을경우 팝업창 생성 \r\n");
      out.write("\t\twindow.open('");
      out.print(cp );
      out.write("/main/idSearch.jsp', 'idsearch','resizable=yes scrollbars=yes width=1000 height=370');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#search_userpw').click(function(){ //비밀번호 찾기를 눌렀을경우 팝업창 생성\r\n");
      out.write("\t\twindow.open(\"");
      out.print(cp );
      out.write("/main/pwSearch.jsp\", 'userpwsearch','resizable=yes scrollbars=yes width=1000 height=370');\r\n");
      out.write("\t});\t\r\n");
      out.write("\t$('#login').click(function(){ //로그인버튼을 눌렀을때\r\n");
      out.write("\t\tif($('#id').val()==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t alert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif($('#password').val()==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t$.post(\"");
      out.print(cp );
      out.write("/userlogin.love\", { \"id\":$('#id').val(),\"password\":$('#password').val() }, function(args){\t\t\r\n");
      out.write("\t \tvar name=args.trim(); //반환된 AJAX값을 name변수에 담아서 (지금은 이름만받았지만 회원코드(1,2,3 중한가지),세션 같이 넘겨야할듯!!)\r\n");
      out.write("\t\tif(name==null||name==\"\"){\r\n");
      out.write("\t\t\talert(\"회원정보가 올바르지않습니다. 확인후 다시 로그인 해 주세요\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\telse//정상적으로 로그인이되었을경우 메인페이지에 name값을 가지고 돌아간다.\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(cp );
      out.write("/main.love\"; \r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("//===============================================================================================\r\n");
      out.write("\t//일반회원탭을 눌렀을 경우\r\n");
      out.write("\t$('#userselect_login').click(function(){\r\n");
      out.write("\t$('#userloginaction').css(\"display\",\"block\");//일반회원 디스플레이block\r\n");
      out.write("\t$('#cmpnyloginaction').css(\"display\",\"none\");//기업회원 디스플레이none\r\n");
      out.write("\t$('#adminloginaction').css(\"display\",\"none\");//관리자 디스플레이none\r\n");
      out.write("\t});\r\n");
      out.write("//===============================================================================================\r\n");
      out.write("\t//기업회원탭을 눌렀을 경우\r\n");
      out.write("\t$('#cmptyselect_login').click(function(){\r\n");
      out.write("\t\t$('#cmpnyloginaction').css(\"display\",\"block\");//기업회원 디스플레이block\r\n");
      out.write("\t\t$('#userloginaction').css(\"display\",\"none\");//일반회원 디스플레이none\r\n");
      out.write("\t\t$('#adminloginaction').css(\"display\",\"none\");//관리자 디스플레이none\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$('#search_cmpnypw').click(function(){ //비밀번호 찾기를 눌렀을경우 팝업창 생성\r\n");
      out.write("\t\t\twindow.open(\"");
      out.print(cp );
      out.write("/main/cmpnyPwSearch.jsp\", 'cmpnypwsearch','resizable=yes scrollbars=yes width=1000 height=370');\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#cmpnylogin').click(function(){ //로그인버튼을 눌렀을때\r\n");
      out.write("\t\t\t if($('#cmpnyid').val()==\"\"){\r\n");
      out.write("\t\t\t alert(\"사업자번호를 입력하세요\");\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t if($('#cmpnypassword').val()==\"\"){\r\n");
      out.write("\t\t\t alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t $.post(\"");
      out.print(cp );
      out.write("/cmpnylogin.love\", { \"cmpnyid\":$('#cmpnyid').val(),\"cmpnypassword\":$('#cmpnypassword').val() }, function(args){\t\t\r\n");
      out.write("\t\t \t var usrname=args.trim(); //반환된 AJAX값을 name변수에 담아서 (지금은 이름만받았지만 회원코드(1,2,3 중한가지),세션 같이 넘겨야할듯!!)\r\n");
      out.write("\t\t\t if(usrname==null||usrname==\"\"){\r\n");
      out.write("\t\t\t\talert(\"회원정보가 올바르지않습니다. 확인후 다시 로그인 해 주세요\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t }\t\r\n");
      out.write("\t\t\t else//정상적으로 로그인이되었을경우 (임시)메인페이지에 name값을 가지고 돌아간다.\r\n");
      out.write("\t\t\t\t location.href=\"");
      out.print(cp );
      out.write("/company/CompanyMain.love\";  \r\n");
      out.write("\t\t\t });\t\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t});\r\n");
      out.write("//===============================================================================================\r\n");
      out.write("\t//관리자탭을 눌렀을 경우\r\n");
      out.write("\t$('#admin').click(function(){\r\n");
      out.write("\t\t$('#adminloginaction').css(\"display\",\"block\");//관리자 디스플레이block\r\n");
      out.write("\t\t$('#userloginaction').css(\"display\",\"none\");//기업회원 디스플레이none\r\n");
      out.write("\t\t$('#cmpnyloginaction').css(\"display\",\"none\");//관리자 디스플레이none\t\t\r\n");
      out.write("\t});\t\r\n");
      out.write("\t$('#adminlogin').click(function(){ //로그인버튼을 눌렀을때\r\n");
      out.write("\t\tif($('#adminid').val()==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t alert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif($('#adminpassword').val()==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t$.post(\"");
      out.print(cp );
      out.write("/adminlogin.love\", { \"adminid\":$('#adminid').val(),\"adminpassword\":$('#adminpassword').val() }, function(args){\t\t\r\n");
      out.write("\t \tvar name=args.trim(); //반환된 AJAX값을 name변수에 담아서 (지금은 이름만받았지만 회원코드(1,2,3 중한가지),세션 같이 넘겨야할듯!!)\r\n");
      out.write("\t\tif(name==null||name==\"\"){\r\n");
      out.write("\t\t\talert(\"회원정보가 올바르지않습니다. 확인후 다시 로그인 해 주세요\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\telse//정상적으로 로그인이되었을경우 메인페이지에 name값을 가지고 돌아간다.\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(cp );
      out.write("/AdminCoMemberList.love\";  //관리자페이지로 바꿔야함!!!!★★★★★★\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 첫번째 헤더영역 -->\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<section></section>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<!-- 탭 로그인창 -->\t\r\n");
      out.write("\t\t<div class=\"container\" id=\"section\">\t\r\n");
      out.write("\t\t\t<ul id=\"myTab\" class=\"nav nav-tabs\">\r\n");
      out.write("\t\t \t \t<li class=\"active\"><a href=\"#userselect_login\" data-toggle=\"tab\" id=\"userselect_login\">개인회원</a></li>\r\n");
      out.write("\t\t  \t\t<li class=\"\"><a href=\"#cmptyselect_login\" data-toggle=\"tab\" id=\"cmptyselect_login\">기업회원</a></li>\r\n");
      out.write("\t\t  \t\t<li class=\"\"><a href=\"#admin\" data-toggle=\"tab\" id=\"admin\">관리자</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<!-- 회원로그인구간 -->\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(cp );
      out.write("/login.love\" id=\"userloginaction\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <div class=\"control-label\"><label for=\"id\">아이디 입력 : </label></div>\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t    <div class=\"control-label\"><label for=\"password\">패스워드 입력 : </label></div>\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <input type=\"text\" class=\"form-control\" name=\"id\" id=\"id\" maxlength=\"16\" placeholder=\"아이디를 입력해주세요\">\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" maxlength=\"16\" placeholder=\"패스워드를 입력해주세요\">\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"><br>\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 로그인 DB확인후 이동-->\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"login\" class=\"btn btn-primary col-sm-8\" style=\"height:85px;\">로그인</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr><br><br>\r\n");
      out.write("\t\t\t\t<!-- 일반회원 아이디/비밀번호 찾기 입력구간 -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"loginimage\"><img src=\"");
      out.print(cp );
      out.write("/images/main/pwd.png\" alt=\"아이디찾기\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t아이디를 잊어버리셨나요?<br>고객님의 아이디를 찾아드립니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"search_id\" class=\"btn btn-primary col-md-offset-3\">아이디찾기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"loginimage\"><img src=\"");
      out.print(cp );
      out.write("/images/main/pwd.png\" alt=\"비밀번호찾기\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t비밀번호를 잊어버리셨나요?<br>고객님의 비밀번호를 찾아드립니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"search_userpw\" class=\"btn btn-primary col-md-offset-3\">비밀번호찾기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"loginimage\"><img src=\"");
      out.print(cp );
      out.write("/images/main/sea.png\" alt=\"회원가입\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t아직 회원이 아니신가요?<br>회원가입후 많은 혜택을 누려보세요.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(cp );
      out.write("/signupcmpnycontroller.love?num=1\"><button type=\"button\" id=\"search_id\" class=\"btn btn-primary col-md-offset-3\">회원가입</button></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 기업회원 로그인구간 -->\r\n");
      out.write("\t\t\t<form action=\"#\" id=\"cmpnyloginaction\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <div class=\"control-label\"><label for=\"id\">사업자번호 입력 : </label></div>\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t    <div class=\"control-label\"><label for=\"password\">패스워드 입력 : </label></div>\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <input type=\"text\" class=\"form-control\" name=\"cmpnyid\" id=\"cmpnyid\" maxlength=\"10\"  placeholder=\"사업자번호(-제외 10자리)를 입력해주세요\">\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <input type=\"password\" class=\"form-control\" name=\"cmpnypassword\" id=\"cmpnypassword\" maxlength=\"16\" placeholder=\"패스워드를 입력해주세요\">\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"><br>\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 로그인 DB확인후 이동-->\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"cmpnylogin\" class=\"btn btn-primary col-sm-8\" style=\"height:85px;\">로그인</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr><br><br>\r\n");
      out.write("\t\t\t\t<!-- 기업회원 비밀번호찾기 및 로그인 회원가입 -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-md-offset-2\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"loginimage\"><img src=\"");
      out.print(cp );
      out.write("/images/main/pwd.png\" alt=\"비밀번호찾기\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t비밀번호를 잊어버리셨나요?<br>고객님의 비밀번호를 찾아드립니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"search_cmpnypw\" class=\"btn btn-primary col-md-offset-3\">비밀번호찾기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"loginimage\"><img src=\"");
      out.print(cp );
      out.write("/images/main/sea.png\" alt=\"회원가입\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t아직 회원이 아니신가요?<br>회원가입후 기업 혜택을 누려보세요.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(cp );
      out.write("/signupcmpnycontroller.love?num=2\"><button type=\"button\" id=\"search_id\" class=\"btn btn-primary col-md-offset-3\">회원가입</button></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 관리자로그인구간 -->\r\n");
      out.write("\t\t\t<form action=\"#\" id=\"adminloginaction\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <div class=\"control-label\"><label for=\"id\">아이디 입력 : </label></div>\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t    <div class=\"control-label\"><label for=\"password\">패스워드 입력 : </label></div>\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <input type=\"text\" class=\"form-control\" name=\"adminid\" id=\"adminid\" maxlength=\"16\" placeholder=\"아이디를 입력해주세요\">\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t                  <li><br>\r\n");
      out.write("\t\t\t                  \t   <input type=\"password\" class=\"form-control\" name=\"adminpassword\" id=\"adminpassword\" maxlength=\"16\" placeholder=\"패스워드를 입력해주세요\">\r\n");
      out.write("\t\t\t                  </li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"><br>\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 로그인 DB확인후 이동-->\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"adminlogin\" class=\"btn btn-primary col-sm-8\" style=\"height:85px;\">로그인</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr><br><br>\r\n");
      out.write("\t\t\t\t<section style=\"padding-bottom:150px;\"></section>\r\n");
      out.write("\t\t\t</form><!-- 관리자폼의종료 -->\r\n");
      out.write("\t\t</div><!-- 전체 컨테이너영역의 종료 -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</section><!-- 전체 섹션영역의 종료 -->\r\n");
      out.write("\t<section></section>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /main/login.jsp(128,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cp }/main/mainGnb.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f1.setParent(null);
    // /main/login.jsp(328,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f1.setUrl((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cp }/main/footer.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
      if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
    }
    return false;
  }
}
