
SELECT C.CMPNY_ID, P.IMG, P.NAME, PO.STT
FROM CMPNY_TBL C, PROD_TBL P, POST_TBL PO
WHERE C.CMPNY_ID = P.CMPNY_ID
AND PO.POST_CD = P.POST_CD
AND STRT IS NULL;


SELECT C.CMPNY_ID, P.IMG, P.NAME, PO.STT
FROM CMPNY_TBL C, PROD_TBL P, POST_TBL PO
WHERE C.CMPNY_ID = P.CMPNY_ID
AND PO.POST_CD = P.POST_CD
AND STRT IS NOT NULL;



SELECT C.CMPNY_ID, A.IMG, A.SBJCT, A.END, PO.STT
FROM CMPNY_TBL C, PROD_TBL PR, ADVT_REQ_TBL A, PMT_TBL PM, AD_CNFM_TBL AD, POST_TBL PO
WHERE C.CMPNY_ID = PR.CMPNY_ID
AND PR.PROD_CD = A.PROD_CD
AND A.ADVT_REQ_CD = PM.ADVT_REQ_CD
AND PM.PMT_CD = AD.PMT_CD
AND PO.POST_CD = AD.POST_CD
AND PR.STRT IS NULL;
















;
-- 일반 상품 기록된 내용 전체 조회
SELECT *
FROM
(
SELECT CC.NAME AS CCNAME, C.CMPNY_ID, P.NAME AS PNAME, PT.NAME AS PTNAME, D.NAME AS DPNAME, D.PRC, I.PTH
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT, DTL_PROD_TBL D, IMG_TBL I
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
AND P.PROD_CD = PT.PROD_CD
AND PT.PROD_TP_CD = D.PROD_TP_CD
AND D.DTL_PROD_CD = I.DTL_PROD_CD
)
WHERE CMPNY_ID = '1111111111';



-- 이미지를 제외한 전체 조회
SELECT *
FROM
(
SELECT CC.NAME AS CCNAME, C.CMPNY_ID, P.NAME AS PNAME, PT.NAME AS PTNAME, D.NAME AS DPNAME, D.PRC
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT, DTL_PROD_TBL D
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
AND P.PROD_CD = PT.PROD_CD
AND PT.PROD_TP_CD = D.PROD_TP_CD
)
WHERE CMPNY_ID = '1111111111';


-- 세부 카테고리르 제외한 전체 조회
SELECT PTNAME
FROM
(
SELECT CC.NAME AS CCNAME, C.CMPNY_ID, P.NAME AS PNAME, PT.NAME AS PTNAME
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
AND P.PROD_CD = PT.PROD_CD
)
WHERE CMPNY_ID = '1111111111';


-- 대 카테고리까지 제외한 항목
SELECT *
FROM
(
SELECT CC.NAME AS CCNAME, C.CMPNY_ID, P.NAME AS PNAME
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
)
WHERE CMPNY_ID = '1111111111';















-- 할인 상품 기록된 내용 조회
SELECT CC.NAME AS CCNAME, C.CMPNY_ID, P.STRT, P.END, P.NAME AS PNAME, PT.NAME AS PTNAME, D.NAME AS DPNAME, D.PRC, I.PTH
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT, DTL_PROD_TBL D, IMG_TBL I
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NOT NULL
AND P.PROD_CD = PT.PROD_CD
AND PT.PROD_TP_CD = D.PROD_TP_CD
AND D.DTL_PROD_CD = I.DTL_PROD_CD;

;;

SELECT *
FROM IMG_TBL;

SELECT *
FROM PROD_TBL;
SELECT *
FROM PROD_TP_TBL;


UPDATE PROD_TP_TBL
SET PROD_CD = 6
WHERE PROD_TP_CD = 20;

COMMIT;

SELECT CCNAME, CMPNY_ID, PNAME, PTNAME, DPNAME, PRC, PTH
FROM CMPNY_PRO_ALL_VIEW;


SELECT CCNAME, CMPNY_ID, HMPG, ADDR, PNAME, IMG FROM CMPNY_PRO_INFO_VIEW WHERE CMPNY_ID = '1111111111';
SELECT PTNAME FROM CMPNY_PRO_BIGCTR_VIEW WHERE CMPNY_ID = '1111111111';

SELECT DPNAME, PRC FROM CMPNY_PRO_SMALLCTR_VIEW WHERE CMPNY_ID = '3333333333' and DPNAME LIKE '%드레스';




SELECT CC.NAME AS CCNAME, C.CMPNY_ID, P.NAME AS PNAME, PT.NAME AS PTNAME, D.NAME AS DPNAME, D.PRC, PT.PROD_TP_CD
FROM CMPNY_CTGY_TBL CC, CMPNY_TBL C, PROD_TBL P, PROD_TP_TBL PT, DTL_PROD_TBL D
WHERE CC.CMPNY_CTGY_ID = C.CMPNY_CTGY_ID
AND C.CMPNY_ID = P.CMPNY_ID
AND P.STRT IS NULL
AND P.PROD_CD = PT.PROD_CD
AND PT.PROD_TP_CD = D.PROD_TP_CD;